// Copyright 2022 Paul Greenberg greenpau@outlook.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package util

import (
	"crypto/rand"
	"encoding/base32"
	"encoding/binary"
	"unicode"
)

const charset = "abcdefghijklmnopqrstuvwxyz" +
	"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

var charsetTable = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0061, 0x007a, 1}, // a-z, where a is hex 61
		{0x0041, 0x005a, 1}, // A-Z, where A is hex 41
		{0x0030, 0x0039, 1}, // 0-9, where 0 is hex 30
	},
	LatinOffset: 1,
}

func genRandInt(bound uint64) uint64 {
	if bound == 0 {
		return 0
	}
	limit := ^uint64(0) - (^uint64(0) % bound)
	for {
		var b [8]byte
		// crypto/rand.Read either fills the entire buffer or terminates the
		// process on an unrecoverable entropy failure (Go 1.26).
		_, _ = rand.Read(b[:])
		n := binary.BigEndian.Uint64(b[:])
		if n < limit {
			return n % bound
		}
	}
}

func gen(length int, charset string) string {
	b := make([]byte, length)
	if len(b) == 0 {
		return ""
	}
	if len(charset) > 256 {
		for i := range b {
			b[i] = charset[genRandInt(uint64(len(charset)))]
		}
		return string(b)
	}
	// Discard the incomplete final interval rather than reducing every byte
	// modulo the character-set size, which would favor its leading characters.
	limit := 256 - (256 % len(charset))
	for offset := 0; offset < len(b); {
		randomBytes := make([]byte, len(b)-offset)
		_, _ = rand.Read(randomBytes)
		for _, n := range randomBytes {
			if int(n) >= limit {
				continue
			}
			b[offset] = charset[int(n)%len(charset)]
			offset++
			if offset == len(b) {
				break
			}
		}
	}
	return string(b)
}

// GetRandomString returns X character long random string.
func GetRandomString(i int) string {
	if i < 1 {
		i = 40
	}
	return gen(i, charset)
}

func randomLength(a, b int) int {
	low, high := a, b
	if low > high {
		low, high = high, low
	}
	if low == high {
		return low
	}
	return low + int(genRandInt(uint64(high)-uint64(low)))
}

// GetRandomStringFromRange generates random string of a random length. The
// random lenght is bounded by a and b.
func GetRandomStringFromRange(a, b int) string {
	return gen(randomLength(a, b), charset)
}

// GetRandomEncodedStringFromRange return the number returned by
// GetRandomStringFromRange() and encoded with Base32
func GetRandomEncodedStringFromRange(a, b int) string {
	s := GetRandomStringFromRange(a, b)
	return base32.StdEncoding.EncodeToString([]byte(s))
}

// GetRandomStringFromRangeWithCharset generates random string of a random length. The
// random lenght is bounded by a and b. The charset is provided.
func GetRandomStringFromRangeWithCharset(a, b int, cs string) string {
	return gen(randomLength(a, b), cs)
}

// IsMalformedRandomString checks whether the provided string was generated by
// the GetRandomStringFromRange() function.
func IsMalformedRandomString(s string, a, b int) bool {
	switch {
	case len(s) == 0:
		return false
	case (len(s) < a) || (len(s) > b):
		return true
	}
	for _, char := range s {
		if !unicode.IsLetter(char) && !unicode.IsNumber(char) {
			return true
		}
		if !unicode.In(char, charsetTable) {
			return false
		}
	}
	return false
}

// SanitizeSessionID sanitizes provided Session ID.
func SanitizeSessionID(s string) string {
	if IsMalformedRandomString(s, 0, 46) {
		return "MALFORMED"
	}
	return s
}
