#!/usr/bin/env python3
"""Generate ACL conditions, rules, and their test matrices with Python 3 and gofmt."""

import argparse
import collections
import logging
from pathlib import Path
import subprocess
import sys
import tempfile
import textwrap


LOG = logging.getLogger(__name__)
ROOT = Path(__file__).resolve().parents[2]
GO_HEADER = '''// Copyright 2022 Paul Greenberg greenpau@outlook.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by assets/scripts/generate_acl.py; DO NOT EDIT.
// Regenerate with: make generate-acl

'''

FIELD_TYPES = collections.OrderedDict({
    'roles':  'ListStr',
    'amr':    'ListStr',
    'github_id': 'Str',
    'github_orgs': 'ListStr',
    'email':  'Str',
    'origin': 'Str',
    'name':   'Str',
    'realm':  'Str',
    'aud':    'ListStr',
    'scopes': 'ListStr',
    'org':    'ListStr',
    'jti':    'Str',
    'iss':    'Str',
    'sub':    'Str',
    'addr':   'Str',
    'method': 'Str',
    'path':   'Str',
})

HTTP_METHODS = ['POST', 'PUT', 'GET', 'PATCH',
                'DELETE', 'HEAD', 'CONNECT', 'OPTIONS', 'TRACE']

LOG_LEVELS = collections.OrderedDict({
    'Debug': {},
    'Info': {},
    'Warn': {},
    'Error': {},
})

VERDICTS = collections.OrderedDict({
    'Deny':         'deny',
    'DenyStop':      'deny stop',
    'Continue':      'continue',
    'Allow':        'allow',
    'AllowStop':    'allow stop'
})

ACTIONS = collections.OrderedDict({
    'Deny':     'Deny',
    'Allow':    'Allow',
})

INPUTDATA = collections.OrderedDict({
    'ListStr': {
        'description': 'a list of strings input',
        'cmp': 'v',
    },
    'Str': {
        'description': 'an input string',
        'cmp': 'v.(string)',
    },
})

CONDS = collections.OrderedDict({
    'ListStr': {
        'description': 'against a list of strings',
        'attrs': {
            'default': [
                'field *field',
                'exprs []*expr',
                'config *config',
            ],
            'Regex': [
                'field *field',
                'exprs []*regexp.Regexp',
                'config *config',
            ],
        },
        'cmp': 'exp',
        'configure': {
            'default': [
                '''
                c.exprs = []*expr{}
                for _, val := range values {
                    c.exprs = append(c.exprs, &expr{
                        value: val,
                    })
                }
                ''',
            ],
            'Regex': [
                '''
                c.exprs = []*regexp.Regexp{}
                for _, val := range values {
                    re, err := regexp.Compile(val)
                    if err != nil {
                        return nil, err
                    }
                    c.exprs = append(c.exprs, re)
                }
                ''',
            ],
        },
    },
    'Str': {
        'description': 'against a string condition',
        'attrs': {
            'default': [
                'field *field',
                'expr *expr',
                'config *config',
            ],
            'Regex': [
                'field *field',
                'expr *regexp.Regexp',
                'config *config',
            ],
        },
        'cmp': 'c.expr',
        'configure': {
            'default': [
                '''
                c.expr = &expr{
                    value: values[0],
                }''',
            ],
            'Regex': [
                '''
		re, err := regexp.Compile(values[0])
                if err != nil {
                    return nil, err
                }
                c.expr = re''',
            ],
        },
    },
})

MATCHES = collections.OrderedDict({
    'Exact': {
        'description': 'exact',
        'expr': 'if %s == %s {',
        'keyword': 'exact',
    },
    'Partial': {
        'description': 'substring',
        'expr': 'if strings.Contains(%s, %s) {',
        'keyword': 'partial',
    },
    'Prefix': {
        'description': 'string prefix',
        'expr': 'if strings.HasPrefix(%s, %s) {',
        'keyword': 'prefix',
    },
    'Suffix': {
        'description': 'string suffix',
        'expr': 'if strings.HasSuffix(%s, %s) {',
        'keyword': 'suffix',
    },
    'Regex': {
        'description': 'regular expressions',
        'expr': 'if %s.MatchString(%s) {',
        'keyword': 'regex',
    },
})


def getLogLevel(s):
    for i in LOG_LEVELS:
        if i in s:
            return i
    return 'Unknown'


def indented(lines, count):
    output = ''
    for line in lines:
        for x in range(count):
            line = ' ' + line
        output += line + '\n'
    for x in range(count-4):
        output += ' '
    return output


def makeCompare(condType, dataType, matchType, negativeMatch):
    output = []
    cmpExpr = None
    exprFunc = MATCHES[matchType]['expr']
    dataKey = INPUTDATA[dataType]['cmp']
    condKey = CONDS[condType]['cmp']
    if matchType != 'Regex':
        condKey += '.value'
        cmpExpr = exprFunc % (dataKey, condKey)
    else:
        cmpExpr = exprFunc % (condKey, dataKey)
    output.append(cmpExpr)
    if negativeMatch:
        output.append('return false')
    else:
        output.append('return true')
    output.append('}')
    return output


def makeMatchFunction(t):
    ct = t['cond_data_type']
    it = t['input_data_type']
    mt = t['match_type']
    negativeMatch = t['negative']
    output = []

    if mt == 'Always':
        output.append('''
        func (c *%s) match(ctx context.Context, v interface{}) bool {
            return true
        }
        ''' % (t['name']))
        return output

    if ct not in CONDS or it not in INPUTDATA:
        raise Exception(
            "bad condition: condition value type %s, input value type: %s" % (ct, it))

    parameter = 'values' if it == 'ListStr' else 'v'
    output.append('func (c *%s) match(ctx context.Context, %s interface{}) bool {' % (t['name'], parameter))
    loops = []
    if ct == 'ListStr':
        loops.append('for _, exp := range c.exprs {')
    if it == 'ListStr':
        loops.append('for _, v := range values.([]string) {')

    # Preserve the existing negative-regex "match any" semantics: one
    # nonmatching pair suffices, whereas the default rejects any matching pair.
    if negativeMatch and mt == 'Regex' and loops:
        output.append('if c.config.matchAny {')
        output.extend(loops)
        output.append('if !%s.MatchString(%s) { return true }' % (CONDS[ct]['cmp'], INPUTDATA[it]['cmp']))
        output.extend('}' for _ in loops)
        output.append('return false\n}')

    output.extend(loops)
    output.extend(makeCompare(ct, it, mt, negativeMatch))
    output.extend('}' for _ in loops)
    output.append('return %s\n}' % ('true' if negativeMatch else 'false'))

    return output


def makeGetConfigFunction(t):
    output = []
    output.append('''
    func (c *%s) getConfig(ctx context.Context) *config {
        return c.config
    }
    ''' % (t['name']))

    return output


def getStructName(inputValueType, condValueType, matchType, negativeMatch):
    if negativeMatch:
        return "rule%sCond%sNegativeMatch%sInput" % (condValueType, matchType, inputValueType)
    return "rule%sCond%sMatch%sInput" % (condValueType, matchType, inputValueType)


def makeTestHeader():
    output = '''
    package acl

    import(
        "context"
        "fmt"
        "reflect"
        "strings"
        "testing"

        "github.com/greenpau/go-authcrunch/internal/tests"
        "github.com/greenpau/go-authcrunch/pkg/errors"
    )
    '''
    return output


def makeRuleTestHeader():
    output = '''
    package acl

    import(
        "context"
        "reflect"
        "strings"
        "testing"

        "github.com/greenpau/go-authcrunch/internal/tests"
        "github.com/greenpau/go-authcrunch/pkg/errors"
        logutil "github.com/greenpau/go-authcrunch/pkg/util/log"
    )
    '''
    return output


def makeTestNewAclRuleTemplate():
    output = '''
    func TestNewAclRule(t *testing.T) {
        var testcases = []struct {
            name      string
            config *RuleConfiguration
            loggerDisabled bool
            want      map[string]interface{}
            shouldErr bool
            err       error
        }{
            %s
        }
        for _, tc := range testcases {
            t.Run(tc.name, func(t *testing.T) {
                var rule aclRule
                ctx := context.Background()
                // t.Logf(tc.name)
                logger := logutil.NewLogger()
                if tc.loggerDisabled {
                    logger = nil
                }
                parsedACLRule, err := newACLRule(ctx, 0, tc.config, logger)
                if tests.EvalErr(t, err, tc.config, tc.shouldErr, tc.err) {
                    return
                }
                rule = parsedACLRule
                ruleConfig := rule.getConfig(ctx)
                got := make(map[string]interface{})
                got["rule_type"] = reflect.TypeOf(rule).String()
                got["config_rule_type"] = ruleConfig.ruleType
                got["comment"] = ruleConfig.comment
                if ruleConfig.logLevel != "" {
                    got["log_level"] = ruleConfig.logLevel
                }
                if ruleConfig.tag == "foobar" {
                    got["tag"] = ruleConfig.tag
                }
                got["action_name"] = getRuleActionName(ruleConfig.action)
                got["default_action_name"] = getRuleActionName(ruleActionUnknown)
                got["reserved_action_name"] = getRuleActionName(ruleActionReserved)
                got["default_verdict_name"] = getRuleVerdictName(ruleVerdictUnknown)
                got["reserved_verdict_name"] = getRuleVerdictName(ruleVerdictReserved)
                tests.EvalObjects(t, "output", tc.want, got)
            })
        }
    }
    '''
    return output


def makeTestNewAclRuleConditionTemplate():
    output = '''
    func TestNewAclRuleCondition(t *testing.T) {
        var testcases = []struct {
            name      string
            condition string
            want      map[string]interface{}
            shouldErr bool
            err       error
        }{
{name: "exact match a list of strings input against a list of strings in groups field",
    condition: `exact match groups barfoo foobar`,
    want: map[string]interface{}{
        "condition_type":          "*acl.ruleListStrCondExactMatchListStrInput",
        "field_name":              "roles",
        "regex_enabled":           false,
        "match_strategy":          "fieldMatchExact",
        "always_true":             false,
        "default_match_strategy":  "fieldMatchUnknown",
        "reserved_match_strategy": "fieldMatchReserved",
        "default_data_type":       "dataTypeUnknown",
        "expr_data_type":          "dataTypeListStr",
        "input_data_type":         "dataTypeListStr",
        "values":                  []string{`barfoo`, `foobar`},
    },
},
            %s
        }
        for _, tc := range testcases {
            t.Run(tc.name, func(t *testing.T) {
                // t.Logf(tc.name)
                // t.Logf(tc.condition)
                ctx := context.Background()
                var cond aclRuleCondition
                parsedACLRuleCondition, err := newACLRuleCondition(ctx, strings.Split(tc.condition, " "))
                if tests.EvalErr(t, err, tc.condition, tc.shouldErr, tc.err) {
                    return
                }
                cond = parsedACLRuleCondition
                condConfig := cond.getConfig(context.Background())
                got := make(map[string]interface{})
                got["field_name"] = condConfig.field
                got["condition_type"] = reflect.TypeOf(cond).String()
                got["match_strategy"] = getMatchStrategyName(condConfig.matchStrategy)
                got["default_match_strategy"] = getMatchStrategyName(fieldMatchUnknown)
                got["reserved_match_strategy"] = getMatchStrategyName(fieldMatchReserved)
                got["regex_enabled"] = condConfig.regexEnabled
                got["always_true"] = condConfig.alwaysTrue
                got["expr_data_type"] = getDataTypeName(condConfig.exprDataType)
                got["input_data_type"] = getDataTypeName(condConfig.inputDataType)
                got["default_data_type"] = getDataTypeName(dataTypeUnknown)
                got["values"] = condConfig.values
                tests.EvalObjects(t, "output", tc.want, got)
            })
        }
    }
    '''
    return output


def makeTestMatchAclRuleConditionTemplateHeader():
    output = '''
    func TestMatchAclRuleCondition(t *testing.T) {
        var testcases = []struct {
            name      string
            condition string
            values    map[string]interface{}
            want      map[string]interface{}
            shouldErr bool
            err       error
        }{
        '''
    return output


def makeTestMatchAclRuleConditionTemplateFooter():
    output = '''}
        for _, tc := range testcases {
            t.Run(tc.name, func(t *testing.T) {
                // t.Logf(tc.name)
                // t.Logf(tc.condition)
                ctx := context.Background()
                var cond aclRuleCondition
                parsedACLRuleCondition, err := newACLRuleCondition(ctx, strings.Split(tc.condition, " "))
                if tests.EvalErr(t, err, tc.condition, false, nil) {
                    return
                }
                cond = parsedACLRuleCondition
                got := make(map[string]interface{})
                got["match"] = cond.match(context.Background(), tc.values["data"])
                // t.Logf("condition: %v", tc.condition)
                // t.Logf("values: %v", tc.values)
                tests.EvalObjects(t, "match result", tc.want, got)
            })
        }
    }
    '''
    return output


def makeTestEvalAclRuleTemplateHeader():
    output = '''
    func TestEvalAclRule(t *testing.T) {
        var testcases = []struct {
            name      string
            config    *RuleConfiguration
            input    map[string]interface{}
            want      map[string]interface{}
            emptyFields bool
            shouldErr bool
            err       error
        }{'''
    return output


def makeTestEvalAclRuleTemplateFooter():
    output = '''}
        for _, tc := range testcases {
            t.Run(tc.name, func(t *testing.T) {
                t.Logf("%s", tc.name)
                var rule aclRule
                ctx := context.Background()
                logger := logutil.NewLogger()
                parsedACLRule, err := newACLRule(ctx, 0, tc.config, logger)
                if tests.EvalErr(t, err, tc.config, tc.shouldErr, tc.err) {
                    return
                }
                rule = parsedACLRule
                ruleType := reflect.TypeOf(rule).String()
                got := make(map[string]interface{})
                got["rule_type"] = ruleType
                if tc.emptyFields {
                    got["empty_fields"] = tc.emptyFields
                    if strings.Contains(ruleType, "Match") {
                        rule.emptyFields(ctx)
                    }
                }
                got["verdict"] = getRuleVerdictName(rule.eval(ctx, tc.input))
                rule.emptyFields(ctx)
                // t.Logf("config: %v", tc.config)
                // t.Logf("input: %v", tc.input)
                tests.EvalObjects(t, "match result", tc.want, got)
            })
        }
    }
    '''
    return output


def makeRuleCodeHeader():
    # TSHOOT: add log
    output = ['''package acl

    import(
        "context"
        "fmt"
        "strings"
        "sync/atomic"

        "go.uber.org/zap"

        "github.com/greenpau/go-authcrunch/pkg/errors"
        cfgutil "github.com/greenpau/go-authcrunch/pkg/util/cfg"
    )

    type ruleVerdict int
    type ruleAction int
    type ruleMatchStrategy int

    const (
        ruleVerdictUnknown ruleVerdict = 0
        ruleVerdictReserved ruleVerdict = 1''']
    for i, k in enumerate(VERDICTS.keys()):
        output.append('    ruleVerdict%s ruleVerdict = %d' % (k, i+2))

    output.append('''
        ruleActionUnknown ruleAction = 0
        ruleActionReserved ruleAction = 1''')
    for i, k in enumerate(ACTIONS.keys()):
        output.append('    ruleAction%s ruleAction = %d' % (k, i+2))
    output.append(')')
    return output


def makeRuleCodeFooter():
    output = []
    output.append('''
    func getRuleVerdictName(s ruleVerdict) (string) {
        switch s {''')
    for i, k in enumerate(VERDICTS.keys()):
        output.append('''case ruleVerdict%s:
        return "ruleVerdict%s"''' % (k, k))

    output.append('''case ruleVerdictReserved:
            return "ruleVerdictReserved"
        }
        return "ruleVerdictUnknown"
    }''')

    output.append('''
    func getRuleActionName(s ruleAction) (string) {
        switch s {''')
    for i, k in enumerate(ACTIONS.keys()):
        output.append('''case ruleAction%s:
        return "ruleAction%s"''' % (k, k))

    output.append('''case ruleActionReserved:
            return "ruleActionReserved"
        }
        return "ruleActionUnknown"
    }''')

    return output


def makeRuleTypeStructs():
    output = []
    output.append('''
    type ruleConfig struct {
        ruleType        string
        comment         string
        fields          []string
        index           map[string]int
        checkFields     map[string]bool
        conditions      []*config
        action          ruleAction
        logEnabled      bool
        tag             string
        logLevel        string
        counterEnabled  bool
        matchAll        bool
    }

    func (cfg *ruleConfig) AsMap() map[string]interface{} {
        m := make(map[string]interface{})
        m["rule_type"] = cfg.ruleType
        if cfg.comment != "" {
            m["comment"] = cfg.comment
        }
        m["fields"] = cfg.fields
        if cfg.index != nil {
            m["index"] = cfg.index
        }
        m["action"] = getRuleActionName(cfg.action)
        m["log_enabled"] = cfg.logEnabled
        if cfg.tag != "" {
            m["tag"] = cfg.tag
        }
        if cfg.logLevel != "" {
            m["log_level"] = cfg.logLevel
        }
        m["counter_enabled"] = cfg.counterEnabled
        m["match_all"] = cfg.matchAll
        conditions := []map[string]interface{}{}
        for _, c := range cfg.conditions {
            conditions = append(conditions, c.AsMap())
        }
        if len(conditions) > 0 {
            m["conditions"] = conditions
        }
        if cfg.checkFields != nil && len(cfg.checkFields) > 0 {
            checkedFields := make(map[string]bool)
            for k, v := range cfg.checkFields {
                checkedFields[k] = v
            }
            m["check_fields"] = checkedFields
        }
        return m
    }

    // RuleConfiguration consists of a list of conditions and and actions
    type RuleConfiguration struct {
        Comment string `json:"comment,omitempty" xml:"comment,omitempty" yaml:"comment,omitempty"`
        Conditions []string `json:"conditions,omitempty" xml:"conditions,omitempty" yaml:"conditions,omitempty"`
        Action string `json:"action,omitempty" xml:"action,omitempty" yaml:"action,omitempty"`
    }

    type aclRule interface {
        eval(context.Context, map[string]interface{}) ruleVerdict
        getConfig(context.Context) *ruleConfig
        emptyFields(context.Context)
    }
    ''')

    acl_struct_types = []

    for field_check in [False, True]:
        # for field_check in [False]:
        for action in ['Allow', 'Deny']:
            # Fast is the default feature. It has no logging or counter.
            # Therefore, it performs faster.
            for feature in ['', 'Logger', 'Counter', 'LoggerCounter']:
                # MatchAll is the default match type..
                for match_type in ['MatchAnyStop', 'MatchAllStop', 'Stop', 'MatchAny', 'MatchAll', '']:
                    if 'Logger' in feature:
                        for logLevel in LOG_LEVELS.keys():
                            t = {}
                            if field_check:
                                t["name"] = "aclRuleFieldCheck%sWith%s%s%s" % (action, logLevel, feature, match_type)
                            else:
                                t["name"] = "aclRule%sWith%s%s%s" % (action, logLevel, feature, match_type)
                            t["action"] = action
                            t["feature"] = feature
                            t["match_type"] = match_type
                            t["log_level"] = logLevel
                            t["field_check"] = field_check

                            if 'Stop' in match_type:
                                t['stop'] = True
                            acl_struct_types.append(t)
                    else:
                        name = None
                        if 'Counter' in feature:
                            if field_check:
                                name = "aclRuleFieldCheck%sWith%s%s" % (action, feature, match_type)
                            else:
                                name = "aclRule%sWith%s%s" % (action, feature, match_type)
                        else:
                            if field_check:
                                name = "aclRuleFieldCheck%s%s%s" % (action, feature, match_type)
                            else:
                                name = "aclRule%s%s%s" % (action, feature, match_type)
                        t = {}
                        t["name"] = name
                        t["action"] = action
                        t["feature"] = feature
                        t["match_type"] = match_type
                        t["log_level"] = 'Unknown'
                        t["field_check"] = field_check

                        if 'Stop' in match_type:
                            t['stop'] = True
                        acl_struct_types.append(t)

    for t in acl_struct_types:
        n = t['name']
        output.append('type %s struct {' % (n))
        output.append('config     *ruleConfig')
        if t['match_type'] in ['Stop', '']:
            output.append('''condition aclRuleCondition
                field     string''')
        else:
            output.append('''conditions []aclRuleCondition
                fields     []string''')
        if 'FieldCheck' in n:
            output.append('checkFields map[string]bool')
        if 'Logger' in n:
            output.append('logger *zap.Logger')
            output.append('tag   string')
        if 'Counter' in n:
            output.append('counterMiss uint64')
            output.append('counterMatch   uint64')
        output.append('}\n')

    for t in acl_struct_types:
        n = t['name']
        output.append('''
        func (rule *%s) getConfig(ctx context.Context) *ruleConfig {
            return rule.config
        }
        ''' % (n))

    for t in acl_struct_types:
        n = t['name']
        output.append('''
        func (rule *%s) emptyFields(ctx context.Context) {''' % (n))

        if 'Match' in n:
            output.append('''rule.fields = make([]string, 0)
            }
            ''')
        else:
            output.append('''rule.field = ""
            }
            ''')

    output.append('''

func newACLRule(ctx context.Context, ruleID int, cfg *RuleConfiguration, logger *zap.Logger) (aclRule, error) {
    return newACLRuleWithFields(ctx, ruleID, cfg, logger, nil)
}

func newACLRuleWithFields(ctx context.Context, ruleID int, cfg *RuleConfiguration, logger *zap.Logger, fieldTypes map[string]dataType) (aclRule, error) {
    var action, logLevel, tag string
    var fieldCondFound bool
    var stopEnabled, logEnabled, counterEnabled, matchAny bool
    var skipNext, lastToken bool
    var conditions []aclRuleCondition
    var condConfigs []*config
    var fields []string
    fieldIndex := make(map[string]int)
    checkFields := make(map[string]bool)

    for i, c := range cfg.Conditions {
        tokens, err := cfgutil.DecodeArgs(c)
        if err != nil {
            return nil, errors.ErrACLRuleSyntaxExtractCondToken.WithArgs(err)
        }
        parsedACLRuleCondition, err := newACLRuleConditionWithFields(ctx, tokens, fieldTypes)
        if err != nil {
            return nil, errors.ErrACLRuleSyntax.WithArgs(err)
        }
        condConfig := parsedACLRuleCondition.getConfig(ctx)
        if fieldTypes[condConfig.field] == dataTypeListStr && condConfig.matchStrategy != fieldFound && condConfig.matchStrategy != fieldNotFound {
            parsedACLRuleCondition = &nonemptyListCondition{parsedACLRuleCondition}
        }
        conditions = append(conditions, parsedACLRuleCondition)
        condConfigs = append(condConfigs, condConfig)
        if _, exists := fieldIndex[condConfig.field]; exists {
            return nil, errors.ErrACLRuleSyntaxDuplicateField.WithArgs(condConfig.field)
        }
        fieldIndex[condConfig.field] = i
        fields = append(fields, condConfig.field)

        // Identify conditions with field exists and not exists match strategies.
        switch condConfig.matchStrategy {
        case fieldFound:
            fieldCondFound = true
            // Covers "field exists".
            checkFields[condConfig.field] = true
        case fieldNotFound:
            // Covers "field not exists".
            fieldCondFound = true
            checkFields[condConfig.field] = false
        }
    }

    tokens, err := cfgutil.DecodeArgs(cfg.Action)
    if err != nil {
        return nil, errors.ErrACLRuleSyntaxExtractActionToken.WithArgs(err)
    }
    for i, token := range tokens {
        if len(tokens) == (i+1) {
            lastToken = true
        }
        if skipNext {
            skipNext = false
            continue
        }
        switch token {
        case "allow", "deny", "reserved":
            if i != 0 {
                return nil, errors.ErrACLRuleSyntaxAllowPreceed.WithArgs(token)
            }
            action = token
            if !lastToken {
                if tokens[i+1] == "any" {
                    matchAny = true
                    skipNext = true
                }
            }
        case "stop":
            stopEnabled = true
        case "counter":
            counterEnabled = true
        case "log":
            logEnabled = true
            if lastToken {
                logLevel = "info"
            } else {
                switch tokens[i+1] {
                case "''' + '", "'.join([x.lower() for x in LOG_LEVELS.keys()]) + '''":
                    logLevel = tokens[i+1]
                    skipNext = true
                default:
                    logLevel = "info"
                }
            }
        case "tag":
            if lastToken {
                return nil, errors.ErrACLRuleSyntaxTagFollowedByValue.WithArgs(token)
            }
            tag = tokens[i+1]
            skipNext = true
        case "and", "with":
        default:
            return nil, errors.ErrACLRuleSyntaxInvalidToken.WithArgs(token)
        }
    }

    ruleTypeName := "aclRule"

    if fieldCondFound {
        ruleTypeName += "FieldCheck"
    }

    // Action directives.
    switch action {
    case "allow":
        ruleTypeName += "Allow"
    case "deny":
        ruleTypeName += "Deny"
    case "reserved":
        ruleTypeName += "Reserved"
    }

    // Log and counter directives.
    if logEnabled || counterEnabled {
        ruleTypeName += "With"
    }
    if logEnabled {
        // logLevel is a validated, nonempty ASCII keyword.
        ruleTypeName += strings.ToUpper(logLevel[:1]) + logLevel[1:] + "Logger"
        if logger == nil {
            return nil, errors.ErrACLRuleSyntaxLoggerNotFound.WithArgs(ruleTypeName) 
        }
    }
    if counterEnabled {
        ruleTypeName += "Counter"
    }

    switch len(conditions) {
    case 0:
        return nil, errors.ErrACLRuleSyntaxCondNotFound
    case 1:
    default:
        // Matching all or any conditions.
        if matchAny {
            ruleTypeName += "MatchAny"
        } else {
            ruleTypeName += "MatchAll"
        }
    }

    // Stop on match.
    if stopEnabled {
        ruleTypeName += "Stop"
    }

    // Tagging.
    if tag == "" {
        tag = fmt.Sprintf("rule%d", ruleID)
    }

    // Build rules.
    var r aclRule
    switch ruleTypeName {''')

    for t in acl_struct_types:
        n = t['name']
        output.append('case "%s":' % (n))
        output.append('''    rule := &%s{
            config: &ruleConfig{
                ruleType: "%s",
                logEnabled: logEnabled,
                counterEnabled: counterEnabled,
                comment: cfg.Comment,''' % (n, n))

        if 'Allow' in n:
            output.append('action: ruleActionAllow,')
        else:
            output.append('action: ruleActionDeny,')

        if 'Logger' in n:
            output.append('tag: tag,')
            output.append('logLevel: logLevel,')

        if 'FieldCheck' in n:
            output.append('checkFields: checkFields,')

        if t["match_type"] in ["Stop", '', "MatchAll", "MatchAllStop"]:
            output.append('matchAll: true,')
        output.append('conditions: condConfigs,')
        output.append('fields: fields,')
        output.append('},')

        if t["match_type"] in ["Stop", '']:
            output.append('condition: conditions[0],')
            output.append('field: fields[0],')
        elif t["match_type"] in ["MatchAll", "MatchAllStop"]:
            output.append('conditions: conditions,')
            output.append('fields: fields,')
        elif t["match_type"] in ["MatchAny", "MatchAnyStop"]:
            output.append('conditions: conditions,')
            output.append('fields: fields,')

        if 'FieldCheck' in n:
            output.append('checkFields: checkFields,')

        if 'Logger' in n:
            output.append('tag: tag,')
            output.append('logger: logger,')
        output.append('}')

        output.append('r  = rule')

    output.append('''default:
        return nil, errors.ErrACLRuleSyntaxTypeUnsupported.WithArgs(ruleTypeName)
        }
    return r, nil
    }\n\n''')

    for t in acl_struct_types:
        n = t['name']
        output.append('func (rule *%s) eval(ctx context.Context, data map[string]interface{}) ruleVerdict {' % (n))

        if t["match_type"] in ["Stop", ''] and 'FieldCheck' in n:
            output.extend(makeRuleEvalMatchSingleWithFieldCheck(t))
        elif t["match_type"] in ["MatchAll", "MatchAllStop"] and 'FieldCheck' in n:
            output.extend(makeRuleEvalMatchAllWithFieldCheck(t))
        elif t["match_type"] in ["MatchAny", "MatchAnyStop"] and 'FieldCheck' in n:
            output.extend(makeRuleEvalMatchAnyWithFieldCheck(t))
        elif t["match_type"] in ["Stop", '']:
            output.extend(makeRuleEvalMatchSingle(t))
        elif t["match_type"] in ["MatchAll", "MatchAllStop"]:
            output.extend(makeRuleEvalMatchAll(t))
        elif t["match_type"] in ["MatchAny", "MatchAnyStop"]:
            output.extend(makeRuleEvalMatchAny(t))
        else:
            raise Exception("unsupported match_type: %s" % (n))
        output.append('}\n\n')
    return output


def makeRuleEvalMatchSingle(t):
    output = []
    name = t['name']
    logLevel = t['log_level']
    action = t['action']
    counter = False
    if 'Counter' in name:
        counter = True
    logger = False
    if 'Logger' in name:
        logger = True

    output.append('''v, found := data[rule.field]
    if !found {''')
    output.append('''return ruleVerdictContinue
    }
    if !rule.condition.match(ctx, v) {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('return ruleVerdictContinue\n}')

    if counter:
        output.append('atomic.AddUint64(&rule.counterMatch, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))

    if 'stop' in t:
        output.append('    return ruleVerdict%sStop' % (action))
    else:
        output.append('    return ruleVerdict%s' % (action))
    return output


def makeRuleEvalMatchSingleWithFieldCheck(t):
    ''' makeRuleEvalMatchSingle - evaluated rules with a single field.'''
    output = []
    name = t['name']
    logLevel = t['log_level']
    action = t['action']
    counter = False
    if 'Counter' in name:
        counter = True
    logger = False
    if 'Logger' in name:
        logger = True

    output.append('''
    for fieldName, shouldExist := range rule.checkFields {
        _, dataFound := data[fieldName]
        if (dataFound && !shouldExist) || (!dataFound && shouldExist) {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')

    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('return ruleVerdictContinue\n}\n}')

    if counter:
        output.append('atomic.AddUint64(&rule.counterMatch, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))

    if 'stop' in t:
        output.append('    return ruleVerdict%sStop' % (action))
    else:
        output.append('    return ruleVerdict%s' % (action))
    return output


def makeRuleEvalMatchAny(t):
    output = []
    name = t['name']
    logLevel = t['log_level']
    action = t['action']
    counter = False
    if 'Counter' in name:
        counter = True
    logger = False
    if 'Logger' in name:
        logger = True

    output.append('''for i, field := range rule.fields {
                        v, found := data[field]
                        if !found {
                            continue
                        }
                        if !rule.conditions[i].match(ctx, v) {
                            continue
                        }''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMatch, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))

    if 'stop' in t:
        output.append('    return ruleVerdict%sStop\n}' % (action))
    else:
        output.append('    return ruleVerdict%s\n}' % (action))
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('    return ruleVerdictContinue')
    return output


def makeRuleEvalMatchAnyWithFieldCheck(t):
    output = []
    name = t['name']
    logLevel = t['log_level']
    action = t['action']
    counter = False
    if 'Counter' in name:
        counter = True
    logger = False
    if 'Logger' in name:
        logger = True

    # TSHOOT: add
    # output.append('''// makeRuleEvalMatchAnyWithFieldCheck''')
    # output.append('log.Printf("%s: hit")' % (name))
    # output.append('log.Printf("'+name+': checkFields: %v", rule.checkFields)')

    output.append('''
    for fieldName, shouldExist := range rule.checkFields {
        _, dataFound := data[fieldName]
        if (dataFound && !shouldExist) || (!dataFound && shouldExist) {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user",          sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('return ruleVerdictContinue\n}\n}')

    output.append('''for i, field := range rule.fields {
                        v, found := data[field]
                        if !found {
                            continue
                        }
                        if !rule.conditions[i].match(ctx, v) {
                            continue
                        }''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMatch, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user",               sanitize(data)))' % (
                logLevel, action.lower()))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))

    if 'stop' in t:
        output.append('    return ruleVerdict%sStop\n}' % (action))
    else:
        output.append('    return ruleVerdict%s\n}' % (action))
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user",         sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('    return ruleVerdictContinue')
    return output


def makeRuleEvalMatchAll(t):
    # This means all match condition has to match in order to get an action.
    output = []
    name = t['name']
    logLevel = t['log_level']
    action = t['action']
    counter = False
    if 'Counter' in name:
        counter = True
    logger = False
    if 'Logger' in name:
        logger = True

    # TSHOOT: add
    # output.append('''// makeRuleEvalMatchAll''')

    output.append('''var matched bool
    for i, field := range rule.fields {
        v, found := data[field]
        if !found {
            return ruleVerdictContinue
        }
        if !rule.conditions[i].match(ctx, v) {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('''return ruleVerdictContinue
        }
        matched = true
    }
    if matched {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMatch, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))
    if 'stop' in t:
        output.append('    return ruleVerdict%sStop\n}' % (action))
    else:
        output.append('    return ruleVerdict%s\n}' % (action))
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('    return ruleVerdictContinue')
    return output


def makeRuleEvalMatchAllWithFieldCheck(t):
    # This means all match condition has to match in order to get an action.
    output = []
    name = t['name']
    logLevel = t['log_level']
    action = t['action']
    counter = False
    if 'Counter' in name:
        counter = True
    logger = False
    if 'Logger' in name:
        logger = True

    # TSHOOT: add
    # output.append('''// makeRuleEvalMatchAllWithFieldCheck''')
    # output.append('log.Printf("%s: hit")' % (name))
    # output.append('log.Printf("'+name+': checkFields: %v", rule.checkFields)')

    output.append('''
    for fieldName, shouldExist := range rule.checkFields {
        _, dataFound := data[fieldName]
        if (dataFound && !shouldExist) || (!dataFound && shouldExist) {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user",          sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('return ruleVerdictContinue\n}\n}')

    output.append('''var matched bool
    for i, field := range rule.fields {
        v, found := data[field]
        if !found {
            return ruleVerdictContinue
        }
        if !rule.conditions[i].match(ctx, v) {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user",          sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('''return ruleVerdictContinue
        }
        matched = true
    }
    if matched {''')
    if counter:
        output.append('atomic.AddUint64(&rule.counterMatch, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.Uint64("counter", rule.counterMatch), zap.String("tag", rule.tag), zap.Any("user",               sanitize(data)))' % (
                logLevel, action.lower()))
        else:
            output.append('rule.logger.%s("acl rule hit", zap.String("action", "%s"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel, action.lower()))
    if 'stop' in t:
        output.append('    return ruleVerdict%sStop\n}' % (action))
    else:
        output.append('    return ruleVerdict%s\n}' % (action))
    if counter:
        output.append('atomic.AddUint64(&rule.counterMiss, 1)')
    if logger:
        if counter:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.Uint64("counter", rule.counterMiss), zap.String("tag", rule.tag), zap.Any("user",          sanitize(data)))' % (logLevel))
        else:
            output.append('rule.logger.%s("acl rule miss", zap.String("action", "continue"), zap.String("tag", rule.tag), zap.Any("user", sanitize(data)))' % (logLevel))
    output.append('    return ruleVerdictContinue')
    return output


def makeConditionHeader():
    output = ['''
    package acl

    import(
        "context"
        "regexp"
        "strings"

        "github.com/greenpau/go-authcrunch/pkg/errors"
    )

    type dataType int
    type fieldMatchStrategy int

    var(
        matchWithStrategyRgx *regexp.Regexp
        matchFieldRgx *regexp.Regexp
    ''']

    output.append('inputDataTypes = map[string]dataType{')
    for k in FIELD_TYPES.keys():
        output.append('"%s": dataType%s,' % (k, FIELD_TYPES[k]))
    output.append('}')

    output.append('''
        inputDataAliases = map[string]string{
            "id": "jti",
            "audience": "aud",
            "expires": "exp",
            "issued": "iat",
            "issuer": "iss",
            "subject": "sub",
            "mail": "email",
            "role": "roles",
            "group": "roles",
            "groups": "roles",
            "scope": "scopes",
            "organization": "org",
            "address": "addr",
            "ip": "addr",
            "ipv4": "addr",
            "http_method": "method",
            "http_path": "path",
        }
    )

    const(
        dataTypeUnknown dataType=0''')

    for i, k in enumerate(CONDS.keys()):
        output.append('    dataType%s dataType = %d' % (k, i+1))
    output.append('    dataTypeAny dataType = %d' % (len(CONDS)+1))

    output.append('''

        fieldMatchUnknown fieldMatchStrategy=0
        fieldMatchReserved fieldMatchStrategy=1''')

    for i, k in enumerate(MATCHES.keys()):
        output.append('    fieldMatch%s fieldMatchStrategy = %d' % (k, i+2))

    output.append('    fieldFound fieldMatchStrategy = %d' % (len(MATCHES)+2))
    output.append('    fieldNotFound fieldMatchStrategy = %d' % (len(MATCHES)+3))
    output.append('    fieldMatchAlways fieldMatchStrategy = %d' % (len(MATCHES)+4))

    output.append('''
    )

    type field struct {
        name string
        length int
    }

    type expr struct {
        value string
        length int
    }

    type config struct {
        field string
        matchStrategy fieldMatchStrategy
        values[]string
        regexEnabled bool
        alwaysTrue bool
        matchAny bool
        exprDataType dataType
        inputDataType dataType
        conditionType string
    }

    type aclRuleCondition interface {
        match(context.Context, interface{}) bool
        getConfig(context.Context) * config
    }

    // ruleAnyCondAlwaysMatchAnyInput returns positive match regardless of
    // input fields, values, or conditions.
    type ruleAnyCondAlwaysMatchAnyInput struct {
       field  *field
       exprs  []*expr
       config *config
    }

    // ruleCondFieldFound returns positive match regardless of input fields, values,
    // or conditions, because the condition is only relevant to ACL rule itself.
    type ruleCondFieldFound struct {
       field  *field
       exprs  []*expr
       config *config
    }

    // ruleCondFieldNotFound returns positive match regardless of input fields, values,
    // or conditions, because the condition is only relevant to ACL rule itself.
    type ruleCondFieldNotFound struct {
       field  *field
       exprs  []*expr
       config *config
    }

    func (c *ruleAnyCondAlwaysMatchAnyInput) match(ctx context.Context, v interface{}) bool {
       return true
    }

    func (c *ruleAnyCondAlwaysMatchAnyInput) getConfig(ctx context.Context) *config {
       return c.config
    }

    func (c *ruleCondFieldFound) match(ctx context.Context, v interface{}) bool {
       return true
    }

    func (c *ruleCondFieldFound) getConfig(ctx context.Context) *config {
       return c.config
    }

    func (c *ruleCondFieldNotFound) match(ctx context.Context, v interface{}) bool {
       return true
    }

    func (c *ruleCondFieldNotFound) getConfig(ctx context.Context) *config {
       return c.config
    }

    ''')
    return output


def makeNewAclRuleCondition(struct_name, match_type, cond_data_type, input_data_type, negativeMatch):
    output = []
    if negativeMatch:
        case = 'case negativeMatch && matchStrategy == fieldMatch%s' % (match_type)
    else:
        case = 'case matchStrategy == fieldMatch%s' % (match_type)
    case += ' && condDataType == dataType%s' % (cond_data_type)
    case += ' && inputDataType == dataType%s:' % (input_data_type)
    output.append(case)

    if negativeMatch:
        output.append("// No match: %s, Condition Type: %s, Input Type: %s" %
                      (match_type, cond_data_type, input_data_type))
    else:
        output.append("// Match: %s, Condition Type: %s, Input Type: %s" %
                      (match_type, cond_data_type, input_data_type))

    regexEnabled = "false"
    if match_type == 'Regex':
        regexEnabled = "true"
    alwaysTrue = "false"
    # Create the condition and config
    output.append('''
        c := & %s{
            config: & config{
                field: fieldName,
                matchStrategy: fieldMatch%s,
                values: values,
                regexEnabled: %s,
                alwaysTrue: %s,
                exprDataType: condDataType,
                inputDataType: inputDataType,
                conditionType: `%s`,
                matchAny: matchAny,
            },
            field: & field{
                name: fieldName,
                length: len(fieldName),
            },
        }''' % (struct_name, match_type, regexEnabled, alwaysTrue, struct_name))

    # Next, configure expressions.
    if cond_data_type in ['Str', 'ListStr']:
        if match_type in CONDS[cond_data_type]['configure']:
            output.extend(CONDS[cond_data_type]['configure'][match_type])
        else:
            output.extend(CONDS[cond_data_type]['configure']['default'])
    else:
        raise Exception("unsupported condition data type: %s" %
                        (cond_data_type))

    output.append('''
        return c, nil
    ''')
    return output


def makeGetMatchStrategyNameFunction():
    output = []
    fnCases = []
    for i, k in enumerate(MATCHES.keys()):
        fnCases.append('''case fieldMatch%s:
        return "fieldMatch%s"''' % (k, k))
    fn = '''
    func getMatchStrategyName(s fieldMatchStrategy)(string) {
        switch s {
        %s
        case fieldFound:
            return "fieldFound"
        case fieldNotFound:
            return "fieldNotFound"
        case fieldMatchAlways:
            return "fieldMatchAlways"
        case fieldMatchReserved:
            return "fieldMatchReserved"
        }
        return "fieldMatchUnknown"
    }
    ''' % ('\n'.join(fnCases))
    output.append(fn.strip())
    return output


def makeGetDataTypeNameFunction():
    output = []
    fnCases = []
    for i, k in enumerate(CONDS.keys()):
        fnCases.append('''case dataType%s:
        return "dataType%s"''' % (k, k))
    fn = '''
    func getDataTypeName(s dataType)(string) {
        switch s {
        %s
        case dataTypeAny:
            return "dataTypeAny"
        }
        return "dataTypeUnknown"
    }
    ''' % ('\n'.join(fnCases))
    output.append(fn.strip())
    return output


def makeNewTypeFunction(type_structs):
    match_keys = []
    for k in MATCHES.keys():
        match_keys.append(k.lower())

    extractMatchStrategy = []
    for k in MATCHES.keys():
        if k.lower() == "reserved":
            continue
        elif k.lower() == "exact":
            extractMatchStrategy.append('''
        case "", "%s":
            return fieldMatch%s''' % (k.lower(), k))
        else:
            extractMatchStrategy.append('''
        case "%s":
            return fieldMatch%s''' % (k.lower(), k))

    output = [r'''

    func init() {
       matchWithStrategyRgx = regexp.MustCompile(`^\s*((?P<negative_match>no)\s)?((?P<match_strategy>exact|partial|prefix|suffix|regex)\s)?match\s*((?P<match_any>any)\s)?`)
       matchFieldRgx = regexp.MustCompile(`^\s*field\s+(?P<field_name>\S+)\s+(?P<field_exists>exists|not\s+exists)\s*$`)
    }

    func (cfg *config) AsMap() map[string]interface{} {
        m := make(map[string]interface{})
        m["field"] = cfg.field
        m["match_strategy"] = getMatchStrategyName(cfg.matchStrategy)
        if len(cfg.values) > 0 {
            m["values"] = cfg.values
        }
        m["regex_enabled"] = cfg.regexEnabled
        m["always_true"] = cfg.alwaysTrue
        m["expr_data_type"] = getDataTypeName(cfg.exprDataType)
        m["input_data_type"] = getDataTypeName(cfg.inputDataType)
        m["condition_type"] = cfg.conditionType
        m["match_any"] = cfg.matchAny
        return m
    }

    func extractMatchStrategy(s string) fieldMatchStrategy {
        switch s {''' + "".join(extractMatchStrategy) + '''
        case "exists":
            return fieldFound
        case "not exists":
            return fieldNotFound
        }
        return fieldMatchUnknown
    }

    func extractFieldNameValues(arr []string) (string, []string) {
        var k string
        var v []string
        var matchFound, fieldFound bool
        for i, a := range arr {
            if a == "match" {
                matchFound = true
                continue
            }
            if !matchFound {
                continue
            }
            if a == "any" && arr[i-1] == "match" {
                continue
            }
            if !fieldFound {
                k = a
                fieldFound = true
                continue
            }
            v = append(v, a)
        }
        if fieldFound {
            if alias, exists := inputDataAliases[k]; exists {
                k = alias
            }
        }
        return k, v
    }

    func validateFieldNameValues(line, k string, v []string) error {
        if k == "" {
            return errors.ErrACLRuleConditionSyntaxMatchFieldNotFound.WithArgs(line)
        }
        if len(v) == 0 {
            return errors.ErrACLRuleConditionSyntaxMatchValueNotFound.WithArgs(line)
        }
        for _, s := range v {
            switch s {
            case "exact", "partial", "prefix", "suffix", "regex":
                return errors.ErrACLRuleConditionSyntaxReservedWordUsage.WithArgs(s, line)
            }
        }
        return nil
    }

    func extractCondDataType(line string, inputDataType dataType, values []string) (dataType, error) {
        switch inputDataType {
        case dataTypeListStr, dataTypeStr:
            if len(values) == 1 {
                return dataTypeStr, nil
            }
            return dataTypeListStr, nil
        case dataTypeAny:
            return dataTypeAny, nil
        }
        return dataTypeUnknown, errors.ErrACLRuleConditionSyntaxCondDataType.WithArgs(line)
    }

    func extractInputDataType(fieldName string) dataType {
        if tp, exists := inputDataTypes[fieldName]; exists {
            return tp
        }
        return dataTypeAny
    }

    func newACLRuleCondition(ctx context.Context, tokens[]string)(aclRuleCondition, error) {
        return newACLRuleConditionWithFields(ctx, tokens, nil)
    }

    func newACLRuleConditionWithFields(ctx context.Context, tokens []string, fieldTypes map[string]dataType) (aclRuleCondition, error) {
        var inputDataType, condDataType dataType
        var matchStrategy fieldMatchStrategy
        var negativeMatch bool
        var fieldName string
        var values []string
        var matchAny bool

        line := strings.Join(tokens, " ")

        switch {
        case line == "match any":
            matchStrategy = fieldMatchAlways
            fieldName = "exp"
            inputDataType = dataTypeAny
            condDataType = dataTypeAny
        case matchFieldRgx.Match([]byte(line)):
            matched := matchFieldRgx.FindStringSubmatch(line)
            for i, k := range matchFieldRgx.SubexpNames() {
                if i > 0 && i <= len(matched) {
                    switch k {
                    case "field_exists":
                        matchStrategy = extractMatchStrategy(matched[i])
                    case "field_name":
                        fieldName = matched[i]
                        if alias, exists := inputDataAliases[fieldName]; exists {
                            fieldName = alias
                        }
                    }
                }
            }
            inputDataType = dataTypeAny
            condDataType = dataTypeAny
        case matchWithStrategyRgx.Match([]byte(line)):
            matched := matchWithStrategyRgx.FindStringSubmatch(line)
            for i, k := range matchWithStrategyRgx.SubexpNames() {
                if i > 0 && i <= len(matched) {
                    switch k {
                    case "match_strategy":
                        matchStrategy = extractMatchStrategy(matched[i])
                        if matchStrategy == fieldMatchUnknown {
                            matchStrategy = fieldMatchExact
                        }
                    case "negative_match":
                        if matched[i] == "no" {
                            negativeMatch = true
                        }
                    case "match_any":
                        if matched[i] == "any" {
                            matchAny = true
                        }
                    }
                }
            }
            fieldName, values = extractFieldNameValues(tokens)
        default:
            return nil, errors.ErrACLRuleConditionSyntaxMatchNotFound.WithArgs(line)
        }

        if matchStrategy == fieldMatchUnknown {
            return nil, errors.ErrACLRuleConditionSyntaxStrategyNotFound.WithArgs(line)
        }

	switch matchStrategy {
        case fieldMatchAlways, fieldFound, fieldNotFound:
        default:
            if err := validateFieldNameValues(line, fieldName, values); err != nil {
                return nil, err
            }
            inputDataType = extractInputDataType(fieldName)
            if customType, ok := fieldTypes[fieldName]; ok {
                inputDataType = customType
            }
            var err error
            condDataType, err = extractCondDataType(line, inputDataType, values)
            if err != nil {
                return nil, err
            }
        }

        switch {
        case matchStrategy == fieldFound:
               // Match: Field Found, Condition Type: Any, Input Type: Any
               c := &ruleCondFieldFound{
                       config: &config{
                               field:         fieldName,
                               matchStrategy: fieldFound,
                               values:        values,
                               regexEnabled:  false,
                               alwaysTrue:    false,
                               exprDataType:  inputDataType,
                               inputDataType: condDataType,
                               conditionType: `ruleCondFieldFound`,
                               matchAny: matchAny,
                       },
                       field: &field{
                               name:   fieldName,
                               length: len(fieldName),
                       },
                       exprs: []*expr{},
               }
               return c, nil
        case matchStrategy == fieldNotFound:
               // Match: Field Found, Condition Type: Any, Input Type: Any
               c := &ruleCondFieldNotFound{
                       config: &config{
                               field:         fieldName,
                               matchStrategy: fieldNotFound,
                               values:        values,
                               regexEnabled:  false,
                               alwaysTrue:    false,
                               exprDataType:  inputDataType,
                               inputDataType: condDataType,
                               conditionType: `ruleCondFieldNotFound`,
                               matchAny: matchAny,
                       },
                       field: &field{
                               name:   fieldName,
                               length: len(fieldName),
                       },
                       exprs: []*expr{},
               }
               return c, nil
        case matchStrategy == fieldMatchAlways:
               // Match: Always, Condition Type: Any, Input Type: Any
               c := &ruleAnyCondAlwaysMatchAnyInput{
                       config: &config{
                               field:         fieldName,
                               matchStrategy: fieldMatchAlways,
                               values:        values,
                               regexEnabled:  false,
                               alwaysTrue:    true,
                               exprDataType:  inputDataType,
                               inputDataType: condDataType,
                               conditionType: `ruleAnyCondAlwaysMatchAnyInput`,
                               matchAny: matchAny,
                       },
                       field: &field{
                               name:   fieldName,
                               length: len(fieldName),
                       },
                       exprs: []*expr{},
               }
               return c, nil''']

    for t in type_structs:
        if ((t['match_type'] + "Match" not in t['name'] and t['match_type'] + "NegativeMatch" not in t['name'])
            or "rule" + t['cond_data_type'] + "Cond" not in t['name']
                or "Match" + t['input_data_type'] + "Input" not in t['name']):
            LOG.debug(t['name'])
            LOG.debug("  %s", t['match_type'] + "Match")
            LOG.debug("  %s", "rule" + t['cond_data_type'] + "Cond")
            LOG.debug("  %s", "Match" + t['input_data_type'] + "Input")
            LOG.debug("  %s", t['cond_data_type'])
            LOG.debug("  %s", t['input_data_type'])
            LOG.debug("  %s", t['match_type'])
            raise Exception("Invalid struct")
            continue
        lines = makeNewAclRuleCondition(t['name'], t['match_type'], t['cond_data_type'], t['input_data_type'], t['negative'])
        for line in lines:
            output.append(line.strip())

    output.append('''
        }
	return nil, errors.ErrACLRuleConditionSyntaxUnsupported.WithArgs(line)
    }
    ''')
    return output


def makeTypeStruct(t):
    output = []
    ct = t['cond_data_type']
    mt = t['match_type']
    negativeMatch = t['negative']
    if negativeMatch:
        matchKeyword = "not match"
    else:
        matchKeyword = "match"

    description = "%s %ses %s" % (
        t['name'], matchKeyword, INPUTDATA[t['input_data_type']]['description'])
    description += " %s" % (CONDS[t['cond_data_type']]['description'])

    if 'List' in t['cond_data_type']:
        description += " where any of the input values %s at least one value of the condition" % (matchKeyword)
    description += " using %s %s." % (
        MATCHES[t['match_type']]['description'], matchKeyword)
    for line in textwrap.wrap(description, width=80):
        output.append("// " + line)
    output.append("type %s struct {" % (t['name']))

    ts_attrs = []
    if mt in CONDS[ct]['attrs']:
        ts_attrs = CONDS[ct]['attrs'][mt]
    else:
        ts_attrs = CONDS[ct]['attrs']['default']
    for ts_attr in ts_attrs:
        output.append("    %s" % (ts_attr))
    output.extend(['}', ''])
    return output


def generateTypeStructs(inputValueType, condValueType, matchType):
    type_structs = []
    for negative in [True, False]:
        for i in inputValueType:
            for j in condValueType:
                for k in matchType:
                    t = {
                        "name": getStructName(i, j, k, negative),
                        "input_data_type": i,
                        "cond_data_type": j,
                        "match_type": k,
                        "negative": negative,
                    }
                    type_structs.append(t)
    return type_structs


def getTestName(fieldName, inputValueType, condValueType, matchType):
    name = "match %s field" % (fieldName)
    name += " %s" % (INPUTDATA[inputValueType]['description']).lower()
    name += " %s" % (CONDS[condValueType]['description']).lower()
    if 'List' in condValueType:
        name += " match any"
    name += " with %s match" % (matchType.lower())
    return name


def generateTestCases():
    output = []
    for f in FIELD_TYPES.keys():
        for m in MATCHES.keys():
            for c in CONDS.keys():
                fieldDataType = FIELD_TYPES[f]
                for i in INPUTDATA.keys():
                    if i != fieldDataType:
                        # LOG.debug("field %s type %s vs. input value type %s",
                        #          f, fieldDataType, i)
                        continue
                    test_name = "%s match" % (MATCHES[m]['keyword'])
                    test_name += " %s" % (INPUTDATA[i]['description'])
                    test_name += " %s" % (CONDS[c]['description'])
                    test_name += " in %s field" % (f)
                    exp_struct_name = "rule%sCond%sMatch%sInput" % (c, m, i)
                    t = {
                        "name": test_name,
                        "struct_name": exp_struct_name,
                        "input_data_type": i,
                        "cond_data_type": c,
                        "match_type": m,
                        "match_keyword": MATCHES[m]['keyword'],
                        "field_name": f,
                    }
                    output.append(t)
                    if m != 'Exact':
                        continue
                    # define default use case (exact)
                    test_name = "default match"
                    test_name += " %s" % (INPUTDATA[i]['description'])
                    test_name += " %s" % (CONDS[c]['description'])
                    test_name += " in %s field" % (f)
                    exp_struct_name = "rule%sCond%sMatch%sInput" % (
                        c, "Exact", i)
                    td = {
                        "name": test_name,
                        "struct_name": exp_struct_name,
                        "input_data_type": i,
                        "cond_data_type": c,
                        "match_type": "Exact",
                        "match_keyword": "",
                        "field_name": f,
                    }
                    output.append(td)
    # raise Exception("XXXX")
    return output


def generateRuleTestCases():
    output = []
    for action in ['Allow', 'Deny']:
        action_keyword = action.lower()
        for feature in ['', 'Logger', 'Counter', 'LoggerCounter']:
            feature_keywords = []
            for k in ['Logger', 'Counter']:
                if k in feature:
                    feature_keywords.append(k.lower())
            for match_type in ['MatchAnyStop', 'MatchAllStop', 'Stop', 'MatchAny', 'MatchAll', '']:
                match_type_keyword = ""
                stop = False
                # Create base name for tests.
                test_name_base = action_keyword
                if 'Match' in match_type:
                    if 'Any' in match_type:
                        test_name_base += " any"
                        match_type_keyword = "any"
                    elif 'All' in match_type:
                        test_name_base += " all"
                        match_type_keyword = "all"
                if 'Stop' in match_type:
                    test_name_base += " and stop processing"
                    stop = True

                # Handle logger test cases.
                if 'Logger' in feature:
                    for log_level in LOG_LEVELS.keys():
                        log_level_keyword = log_level.lower()
                        test_name = "%s" % (test_name_base)
                        test_name += " with %s logging" % (log_level_keyword)
                        if 'counter' in feature_keywords:
                            test_name += " and with counter"
                        else:
                            test_name += " and without counter"
                        t = {
                            "name": test_name,
                            "struct_name": "aclRule%sWith%s%s%s" % (action, log_level, feature, match_type),
                            "action": action,
                            "action_keyword": action_keyword,
                            "feature": feature,
                            "feature_keywords": feature_keywords,
                            "match_type": match_type,
                            "match_type_keyword": match_type_keyword,
                            "stop": stop,
                            "log_level": log_level,
                            "log_level_keyword": log_level_keyword,
                        }
                        output.append(t)

                else:
                    # Handle counter and default test cases.
                    test_name = "%s" % (test_name_base)
                    if 'Counter' in feature:
                        test_name += " with counter and without logging"
                        exp_struct_name = "aclRule%sWith%s%s" % (action, feature, match_type)
                    else:
                        test_name += " without counter and logging"
                        exp_struct_name = "aclRule%s%s%s" % (action, feature, match_type)
                    t = {
                        "name": test_name,
                        "struct_name": exp_struct_name,
                        "action": action,
                        "action_keyword": action_keyword,
                        "feature": feature,
                        "feature_keywords": feature_keywords,
                        "match_type": match_type,
                        "match_type_keyword": match_type_keyword,
                        "stop": stop,
                        "log_level": 'Unknown',
                        "log_level_keyword": 'unknown',
                    }
                    output.append(t)
    return output


def generateRuleCode():
    output = []
    output.extend(makeRuleCodeHeader())
    output.extend(makeRuleTypeStructs())
    output.extend(makeRuleCodeFooter())
    return '\n'.join(output)


def generateConditionCode():
    output = []
    inputValueType = INPUTDATA.keys()
    condValueType = CONDS.keys()
    matchType = MATCHES.keys()

    type_structs = generateTypeStructs(inputValueType, condValueType, matchType)
    output.extend(makeConditionHeader())

    for t in type_structs:
        output.extend(makeTypeStruct(t))

    for t in type_structs:
        output.append('')
        for line in makeMatchFunction(t):
            output.append(line.strip())

    for t in type_structs:
        output.append('')
        for line in makeGetConfigFunction(t):
            output.append(line.strip())

    output.extend(makeNewTypeFunction(type_structs))
    output.extend(makeGetMatchStrategyNameFunction())
    output.extend(makeGetDataTypeNameFunction())
    return '\n'.join(output)


def makeTestMatchAclRuleCondition(t):
    output = []
    for status in ['success', 'error']:
        name = t['name']
        if status == 'success':
            name = 'failed %s' % (name)

        if t['cond_data_type'] == 'ListStr':
            cdv = "barfoo foobar"
        elif t['cond_data_type'] == 'Str':
            cdv = "foobar"
        else:
            raise Exception("unsupported condition data type: %s" % (t['cond_data_type']))

        if t['input_data_type'] == 'ListStr':
            idt = '[]string{"oograb", "foobar"}'
            if status == 'error':
                idt = '[]string{"billy", "bones"}'
        elif t['input_data_type'] == 'Str':
            idt = '"foobar"'
            if status == 'error':
                idt = '"billy"'
        else:
            raise Exception("unsupported condition data type: %s" % (t['input_data_type']))

        tc = '{'
        tc += '    name: "%s",\n' % (name)
        tc += '    condition: `%s match %s %s`,\n' % (t['match_keyword'], t['field_name'], cdv)
        tc += '    values: map[string]interface{}{\n'
        tc += '        "data": %s,\n' % (idt)
        tc += '    },\n'
        tc += '    want: map[string]interface{}{\n'
        result = "false"
        for w in cdv.split(' '):
            if w in idt:
                result = "true"
        tc += '        "match": %s,\n' % (result)
        tc += '    },\n'
        tc += '},\n'
        output.append(tc.strip())
    return output


def makeTestNewAclRule(t):
    output = []
    cfg = {}

    match_type_keyword = t['match_type_keyword']
    match_action_keyword = t['action_keyword']
    feature_keywords = t['feature_keywords']
    log_level_keyword = t['log_level_keyword']
    stop = t['stop']
    for status in ['success', 'error']:
        ruleCfg = ['&RuleConfiguration{']
        comment = "foobar barfoo"
        ruleCfg.append('Comment: "%s",' % (comment))
        if match_type_keyword == "":
            if status == "success":
                ruleCfg.append('Conditions: []string{"exact match roles foobar"},')
            else:
                ruleCfg.append('Conditions: []string{"exact roles foobar"},')
        else:
            ruleCfg.append('Conditions: []string{')
            if status == "success":
                ruleCfg.append('"exact match roles foobar",')
                ruleCfg.append('"exact match org nyc",')
            else:
                ruleCfg.append('"exact match roles foobar",')
                ruleCfg.append('"foo org nyc",')
            ruleCfg.append('},')

        action_tokens = [match_action_keyword]
        action = 'ruleAction' + t['action']

        if match_type_keyword == 'any':
            action_tokens.append('any')
        if stop:
            action_tokens.append('stop')
        if 'counter' in feature_keywords:
            action_tokens.append('counter')
        if 'logger' in feature_keywords:
            action_tokens.append('log')
            if t['struct_name'] == 'aclRuleDenyWithInfoLoggerStop':
                action_tokens.extend(['tag', 'foobar'])
                t['tag'] = 'foobar'
            else:
                action_tokens.append(log_level_keyword)
        ruleCfg.append("Action: `%s`," % (' '.join(action_tokens)))
        ruleCfg.append('}')
        if status == 'success':
            cfg['config'] = ruleCfg
            cfg['metadata'] = t

        tc = '{'
        if status == 'success':
            tc += '    name: "%s",\n' % (t['name'])
        else:
            tc += '    name: "failed %s",\n' % (t['name'])
        tc += '    config: %s,\n' % ('\n'.join(ruleCfg))

        if status == 'success':
            tc += '    want: map[string]interface{}{\n'
            tc += '        "rule_type": "*acl.%s",\n' % (t['struct_name'])
            tc += '        "config_rule_type": "%s",\n' % (t['struct_name'])
            tc += '        "comment": "%s",\n' % (comment)
            tc += '        "action_name": "%s",\n' % (action)
            tc += '        "default_verdict_name": "ruleVerdictUnknown",\n'
            tc += '        "reserved_verdict_name": "ruleVerdictReserved",\n'
            tc += '        "default_action_name": "ruleActionUnknown",\n'
            tc += '        "reserved_action_name": "ruleActionReserved",\n'
            if 'tag' in t:
                tc += '        "tag": "%s",\n' % (t['tag'])
            if t['log_level_keyword'] != "unknown":
                tc += '        "log_level": "%s",\n' % (t['log_level_keyword'])
            tc += '    },\n'
        else:
            tc += '    shouldErr: true,\n'
            if match_type_keyword == "":
                tc += '    err: errors.ErrACLRuleSyntax.WithArgs(errors.ErrACLRuleConditionSyntaxMatchNotFound.WithArgs("exact roles foobar")),\n'
            else:
                tc += '    err: errors.ErrACLRuleSyntax.WithArgs(errors.ErrACLRuleConditionSyntaxMatchNotFound.WithArgs("foo org nyc")),\n'
        tc += '},\n'

        output.append(tc.strip())
    return cfg, output


def makeTestNewAclRuleCondition(t):
    output = []
    for status in ['success', 'error']:
        if status == 'success':
            if t['cond_data_type'] == 'ListStr':
                cdv = "barfoo foobar"
            elif t['cond_data_type'] == 'Str':
                cdv = "foobar"
            else:
                raise Exception("unsupported condition data type: %s" % (t['cond_data_type']))

            tc = '{'
            tc += '    name: "%s",\n' % (t['name'])
            tc += '    condition: `%s match %s %s`,\n' % (
                t['match_keyword'], t['field_name'], cdv)
            tc += '    want: map[string]interface{}{\n'
            tc += '        "condition_type": "*acl.%s",\n' % (t['struct_name'])
            tc += '        "field_name": "%s",\n' % (t['field_name'])
            # regex match
            if t['match_type'] == 'Regex':
                tc += '        "regex_enabled": true,\n'
            else:
                tc += '        "regex_enabled": false,\n'
            tc += '        "match_strategy": "fieldMatch%s",\n' % (
                t['match_type'])
            tc += '        "always_true": false,\n'
            tc += '        "default_match_strategy": "fieldMatchUnknown",\n'
            tc += '        "reserved_match_strategy": "fieldMatchReserved",\n'
            tc += '        "default_data_type": "dataTypeUnknown",\n'
            tc += '        "expr_data_type": "dataType%s",\n' % (t["cond_data_type"])
            tc += '        "input_data_type": "dataType%s",\n' % (t["input_data_type"])
            tc += '        "values": []string{`' + '`,`'.join(cdv.split(' ')) + '`},\n'
            tc += '    },\n'
            tc += '},\n'
            output.append(tc.strip())
            continue
        if t['match_keyword'] == 'regex':
            if t['cond_data_type'] == 'ListStr':
                cdv = "barfoo (foobar|raboff"
                errMsg = "error parsing regexp: missing closing ): `(foobar|raboff`"
            elif t['cond_data_type'] == 'Str':
                cdv = "foobar|raboff)"
                errMsg = "error parsing regexp: unexpected ): `foobar|raboff)`"
            else:
                raise Exception("unsupported condition data type: %s" % (t['cond_data_type']))
            tc = '''{
                name: "failed %s",
                condition: `%s match %s %s`,
                shouldErr: true,
                err: fmt.Errorf("%s"),
            },
            ''' % (t['name'], t['match_keyword'], t['field_name'], cdv, errMsg)

            output.append(tc.strip())
            continue
    return output


def makeTestNewAclRuleConditionCustomFailed():
    output = []
    # These test cases become a part of TestNewAclRuleCondition.
    test_cases = [
        {
            "name": "invalid condition syntax match not found",
            "condition": "exact",
            "error": 'errors.ErrACLRuleConditionSyntaxMatchNotFound.WithArgs("exact")',
        },
        {
            "name": "invalid condition syntax field name not found",
            "condition": "exact match",
            "error": 'errors.ErrACLRuleConditionSyntaxMatchFieldNotFound.WithArgs("exact match")',
        },
        {
            "name": "invalid condition syntax not matching field values",
            "condition": "exact match roles",
            "error": 'errors.ErrACLRuleConditionSyntaxMatchValueNotFound.WithArgs("exact match roles")',
        },
        {
            "name": "invalid condition syntax use of reserved keyword",
            "condition": "exact match roles partial",
            "error": 'errors.ErrACLRuleConditionSyntaxReservedWordUsage.WithArgs("partial", "exact match roles partial")',
        },
        {
            "name": "invalid condition syntax unsupported field",
            "condition": "exact match bootstrap yes",
            "error": 'errors.ErrACLRuleConditionSyntaxUnsupported.WithArgs("exact match bootstrap yes")',
        },
        {
            "name": "invalid condition syntax use of reserved type",
            "condition": "reserved match roles anonymous",
            "error": 'errors.ErrACLRuleConditionSyntaxMatchNotFound.WithArgs("reserved match roles anonymous")',
        },
    ]
    for t in test_cases:
        tc = '''{
            name: "%s",
            condition: `%s`,
            shouldErr: true,
            err: %s,
        },
        ''' % (t['name'], t['condition'], t['error'])
        output.append(tc.strip())
    return output


def makeTestNewAclRuleCustomFailed():
    output = []
    test_cases = [
        {
            "name": "invalid rule syntax failed to extract condition tokens",
            "conditions": [
                "",
            ],
            "action": "deny",
            "error": 'errors.ErrACLRuleSyntaxExtractCondToken.WithArgs("EOF")',
        },
        {
            "name": "invalid rule syntax duplicate field in conditions",
            "conditions": [
                "match roles anonymous guest",
                "match roles anonymous guest",
            ],
            "action": "deny",
            "error": 'errors.ErrACLRuleSyntaxDuplicateField.WithArgs("roles")',
        },
        {
            "name": "invalid rule syntax failed to extract action tokens",
            "conditions": [
                "match roles anonymous guest",
            ],
            "action": "",
            "error": 'errors.ErrACLRuleSyntaxExtractActionToken.WithArgs("EOF")',
        },
        {
            "name": "invalid rule syntax, allow misplaced in action",
            "conditions": [
                "match roles anonymous guest",
            ],
            "action": "allow allow any",
            "error": 'errors.ErrACLRuleSyntaxAllowPreceed.WithArgs("allow")',
        },
        {
            "name": "invalid rule syntax, tag without value",
            "conditions": [
                "match roles anonymous guest",
            ],
            "action": "allow any tag",
            "error": 'errors.ErrACLRuleSyntaxTagFollowedByValue.WithArgs("tag")'
        },
        {
            "name": "invalid rule syntax, unsupported keyword",
            "conditions": [
                "match roles anonymous guest",
            ],
            "action": "allow any foobar",
            "error":  'errors.ErrACLRuleSyntaxInvalidToken.WithArgs("foobar")',
        },
        {
            "name": "invalid rule syntax, log with no logger available",
            "conditions": [
                "match roles anonymous guest",
            ],
            "action": "allow any log",
            "disable_logger": "true",
            "error":  'errors.ErrACLRuleSyntaxLoggerNotFound.WithArgs("aclRuleAllowWithInfoLogger")',
        },
        {
            "name": "invalid rule syntax, no conditions",
            "conditions": [],
            "action": "allow any log",
            "error":  'errors.ErrACLRuleSyntaxCondNotFound',
        },
        {
            "name": "invalid rule syntax, reserved action",
            "conditions": [
                "match roles anonymous guest",
            ],
            "action": "reserved any log",
            "error":  'errors.ErrACLRuleSyntaxTypeUnsupported.WithArgs("aclRuleReservedWithInfoLogger")',
        },
    ]
    for t in test_cases:
        logger_disabled = "false"
        if 'disable_logger' in t:
            logger_disabled = "true"
        tc = '''{
            name: "%s",
            config: &RuleConfiguration{\n''' % (t['name'])
        if len(t['conditions']) > 0:
            tc += '''Conditions: []string{
                    %s
                },''' % ('"' + '",\n"'.join(t['conditions']) + '",\n')
        tc += '''Action: "%s",
            },
            loggerDisabled: %s,
            shouldErr: true,
            err: %s,
        },
        ''' % (t['action'], logger_disabled, t['error'])
        output.append(tc.strip())
    return output


def makeTestEvalAclRule(t):
    output = []
    LOG.debug("entry: %s", t)

    for k in VERDICTS.keys():
        name = t['metadata']['name']
        name += ' with %s verdict' % (VERDICTS[k])
        if 'Stop' in k and 'Stop' not in t['metadata']['struct_name']:
            continue

        if k in ['Allow', 'Deny'] and 'Stop' in t['metadata']['struct_name']:
            continue

        if "Allow" in k or "Deny" in k:
            if 'DenyStop' in t['metadata']['struct_name'] and 'DenyStop' not in k:
                continue
            if 'AllowStop' in t['metadata']['struct_name'] and 'AllowStop' not in k:
                continue
            if 'Deny' in t['metadata']['struct_name'] and "Allow" in k:
                continue
            if 'Allow' in t['metadata']['struct_name'] and "Deny" in k:
                continue
            if 'All' in t['metadata']['struct_name']:
                req = [{
                    "roles": {
                        "value": ["foobar"],
                        "type": "ListStr",
                    },
                    "org": {
                        "value": ["nyc"],
                        "type": "ListStr",
                    },
                }]
            else:
                req = [{
                    "roles": {
                        "value": ["foobar"],
                        "type": "ListStr",
                    },
                }]
        elif "Continue" in k:
            req = [
                {
                    "name": {
                        "value": "John Smith",
                        "type": "Str",
                    },
                    "roles": {
                        "value": ["barfoo"],
                        "type": "ListStr",
                    },
                },
                {
                    "name": {
                        "value": "John Smith",
                        "type": "Str",
                    },
                },
                {
                    "empty_fields": True,
                    "name": {
                        "value": "John Smith",
                        "type": "Str",
                    },
                    "roles": {
                        "value": ["barfoo"],
                        "type": "ListStr",
                    },
                },
                {
                    "empty_fields": True,
                    "name": {
                        "value": "John Smith",
                        "type": "Str",
                    },
                },
            ]
        for i, entry in enumerate(req):
            tc = '{'
            if i > 0:
                tc += '    name: "%s %d",\n' % (name, i)
            else:
                tc += '    name: "%s",\n' % (name)
            tc += '    config: %s,' % ('\n'.join(t['config']))
            tc += '    input: map[string]interface{}{\n'
            for field in entry:
                if field == "empty_fields":
                    continue
                if entry[field]['type'] == 'ListStr':
                    tc += '      "%s": []string{"%s"},\n' % (field, '", "'.join(entry[field]['value']))
                elif entry[field]['type'] == 'Str':
                    tc += '      "%s": "%s",\n' % (field, entry[field]['value'])
            tc += '    },\n'
            for field in entry:
                if field != "empty_fields":
                    continue
                tc += 'emptyFields: true,\n'
            tc += '    want: map[string]interface{}{\n'
            tc += '        "verdict": getRuleVerdictName(ruleVerdict%s),\n' % (k)
            for field in entry:
                if field != "empty_fields":
                    continue
                tc += '"empty_fields": true,\n'
            tc += '        "rule_type": "*acl.%s",\n' % (t['metadata']['struct_name'])
            tc += '    },\n'
            tc += '},\n'
            output.append(tc.strip())
    return output


def generateConditionTests():
    output = []
    header = makeTestHeader()
    output.append(header)
    test_cases = generateTestCases()
    # LOG.debug(pformat(test_cases, width=260))

    new_cond_tests = []
    for t in test_cases:
        # LOG.debug(pformat(t, width=260))
        # LOG.debug(pformat(t))
        new_cond_test = makeTestNewAclRuleCondition(t)
        new_cond_tests.extend(new_cond_test)
    custom_failed_new_cond_tests = makeTestNewAclRuleConditionCustomFailed()
    new_cond_tests.extend(custom_failed_new_cond_tests)
    tmplAclRuleConditions = makeTestNewAclRuleConditionTemplate()
    output.append(tmplAclRuleConditions % (''.join(new_cond_tests)))
    match_cond_tests = []
    for t in test_cases:
        # LOG.debug(pformat(t, width=260))
        # LOG.debug(pformat(t))
        match_cond_test = makeTestMatchAclRuleCondition(t)
        match_cond_tests.extend(match_cond_test)
    output.append(makeTestMatchAclRuleConditionTemplateHeader())
    output.append(''.join(match_cond_tests))
    output.append(makeTestMatchAclRuleConditionTemplateFooter())
    return '\n'.join(output)


def generateRuleTests():
    output = []
    output.append(makeRuleTestHeader())
    test_cases = generateRuleTestCases()
    new_rule_tests = []
    eval_tests = []
    for t in test_cases:
        rule_cfg, rule_test = makeTestNewAclRule(t)
        new_rule_tests.extend(rule_test)
        eval_tests.append(rule_cfg)

    custom_failed_new_rule_tests = makeTestNewAclRuleCustomFailed()
    new_rule_tests.extend(custom_failed_new_rule_tests)
    tmplAclRules = makeTestNewAclRuleTemplate()
    output.append(tmplAclRules % (''.join(new_rule_tests)))
    eval_rule_tests = []
    for t in eval_tests:
        eval_rule_test = makeTestEvalAclRule(t)
        eval_rule_tests.extend(eval_rule_test)
    output.append(makeTestEvalAclRuleTemplateHeader())
    output.append(''.join(eval_rule_tests))
    output.append(makeTestEvalAclRuleTemplateFooter())
    return '\n'.join(output)


def render():
    """Render and format every artifact before touching any destination."""
    generators = {
        'condition.go': generateConditionCode,
        'condition_test.go': generateConditionTests,
        'rule.go': generateRuleCode,
        'rule_test.go': generateRuleTests,
    }
    output = {}
    for name, generate in generators.items():
        source = GO_HEADER + generate().lstrip()
        result = subprocess.run(['gofmt'], input=source.encode('utf-8'), capture_output=True, check=False)
        if result.returncode:
            raise ValueError('gofmt failed for %s: %s' % (name, result.stderr.decode('utf-8', errors='replace').strip()))
        output[name] = result.stdout
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='report missing or stale generated files without writing')
    args = parser.parse_args()
    try:
        output = render()
        destination = ROOT / 'pkg/acl'
        changed = [name for name, content in output.items()
                   if not (destination / name).exists() or (destination / name).read_bytes() != content]
        if args.check:
            for name in changed:
                print('out of date: pkg/acl/%s (run make generate-acl)' % name, file=sys.stderr)
            return 1 if changed else 0
        if changed:
            destination.mkdir(parents=True, exist_ok=True)
            # Stage all files first; replace each destination with a complete file.
            # A rendering, formatting, or staging failure leaves existing files intact.
            with tempfile.TemporaryDirectory(prefix='.generate-acl-', dir=destination) as directory:
                staged = Path(directory)
                for name in changed:
                    path = staged / name
                    path.write_bytes(output[name])
                    if (destination / name).exists():
                        path.chmod((destination / name).stat().st_mode & 0o777)
                for name in changed:
                    (staged / name).replace(destination / name)
                    print('generated pkg/acl/%s' % name)
        else:
            print('ACL generated files are up to date')
        return 0
    except (OSError, ValueError) as exc:
        print('generate-acl: %s' % exc, file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
