// Copyright 2026 Paul Greenberg greenpau@outlook.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authn

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"errors"
	"math/big"
	"net/http"
	"net/http/httptest"
	"strconv"
	"sync"
	"testing"

	jwtlib "github.com/golang-jwt/jwt/v5"
	"go.uber.org/zap"

	"github.com/greenpau/go-authcrunch/internal/tests"
	"github.com/greenpau/go-authcrunch/pkg/apiauth"
	"github.com/greenpau/go-authcrunch/pkg/authn/cookie"
	"github.com/greenpau/go-authcrunch/pkg/authn/ui"
	"github.com/greenpau/go-authcrunch/pkg/kms"
	"github.com/greenpau/go-authcrunch/pkg/requests"
)

func newJWKSPortal(t *testing.T, directives ...string) *Portal {
	t.Helper()
	cfg, err := kms.NewCryptoKeyStoreConfig(directives)
	if err != nil {
		t.Fatal(err)
	}
	ks, err := kms.NewCryptoKeyStore(cfg, zap.NewNop())
	if err != nil {
		t.Fatal(err)
	}
	// Missing session/authorization/UI runtimes ensure discovery is independent
	// of login state and does not invoke authenticated handlers.
	return &Portal{config: &PortalConfig{UI: &ui.Parameters{}}, cookie: &cookie.Factory{}, keystore: ks, logger: zap.NewNop()}
}

func requestJWKS(t *testing.T, p *Portal, method, target string, headers map[string]string) *httptest.ResponseRecorder {
	t.Helper()
	r := httptest.NewRequest(method, "https://auth.example.test"+target, nil)
	for k, v := range headers {
		r.Header.Set(k, v)
	}
	w := httptest.NewRecorder()
	rr := requests.NewRequest()
	if err := p.ServeHTTP(context.Background(), w, r, rr); err != nil {
		t.Fatal(err)
	}
	if len(w.Header().Values("Set-Cookie")) != 0 || w.Header().Get("Location") != "" || rr.Response.Authenticated {
		t.Fatal("JWKS request changed session state or redirected")
	}
	if w.Header().Get("Cache-Control") != "no-store" || w.Header().Get("X-Content-Type-Options") != "nosniff" {
		t.Fatal("missing JWKS cache or content-type protection")
	}
	return w
}

func TestPortalJWKS(t *testing.T) {
	p := newJWKSPortal(t)
	cases := []struct {
		name, path string
		headers    map[string]string
	}{
		{"root", "/.well-known/jwks.json", nil},
		{"default mount", "/auth/.well-known/jwks.json", nil},
		{"custom mount", "/xauth/.well-known/jwks.json", nil},
		{"nested mount", "/tenant/xauth/.well-known/jwks.json", nil},
		{"API in mount", "/api/xauth/.well-known/jwks.json", nil},
		{"QR code in mount", "/qrcode/xauth/.well-known/jwks.json", nil},
		{"profile in mount", "/profile/xauth/.well-known/jwks.json", nil},
		{"JSON query", "/xauth/.well-known/jwks.json?format=json", nil},
		{"unrelated query", "/xauth/.well-known/jwks.json?redirect_url=https://other.example.test", nil},
		{"JSON content type", "/xauth/.well-known/jwks.json", map[string]string{"Content-Type": "application/json", "Accept": "application/json"}},
		{"JWK content negotiation", "/xauth/.well-known/jwks.json", map[string]string{"Accept": "application/jwk-set+json"}},
		{"invalid credentials ignored", "/xauth/.well-known/jwks.json", map[string]string{"Authorization": "Bearer invalid", "Cookie": "access_token=invalid; AUTHP_SESSION_ID=invalid"}},
		{"encoded endpoint", "/xauth/%2ewell-known/%6awks.json", nil},
	}
	var reference []byte
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			w := requestJWKS(t, p, "GET", tc.path, tc.headers)
			if w.Code != http.StatusOK {
				t.Fatalf("got status %d", w.Code)
			}
			if w.Header().Get("Content-Type") != "application/jwk-set+json" {
				t.Fatal("unexpected content type")
			}
			if w.Header().Get("Content-Length") != strconv.Itoa(w.Body.Len()) {
				t.Fatal("incorrect content length")
			}
			var set struct {
				Keys []map[string]string `json:"keys"`
			}
			if err := json.Unmarshal(w.Body.Bytes(), &set); err != nil {
				t.Fatal(err)
			}
			if len(set.Keys) != 1 || set.Keys[0]["kty"] != "EC" || set.Keys[0]["alg"] != "ES512" {
				t.Fatal("missing autogenerated public signing key")
			}
			if reference == nil {
				reference = append([]byte(nil), w.Body.Bytes()...)
			}
			if !bytes.Equal(reference, w.Body.Bytes()) {
				t.Fatal("mount, headers or query changed the public keys")
			}
		})
	}
	head := requestJWKS(t, p, "HEAD", "/xauth/.well-known/jwks.json", nil)
	if head.Code != http.StatusOK || head.Body.Len() != 0 || head.Header().Get("Content-Length") != strconv.Itoa(len(reference)) || head.Header().Get("Content-Type") != "application/jwk-set+json" {
		t.Fatal("HEAD does not describe GET without a body")
	}
	for _, method := range []string{"POST", "PUT", "DELETE", "PATCH", "OPTIONS", "TRACE"} {
		t.Run(method, func(t *testing.T) {
			w := requestJWKS(t, p, method, "/xauth/.well-known/jwks.json", nil)
			if w.Code != http.StatusMethodNotAllowed || w.Header().Get("Allow") != "GET, HEAD" || w.Body.Len() != 0 {
				t.Fatal("unsupported method was not rejected")
			}
		})
	}
}

func TestPortalJWKSUnavailable(t *testing.T) {
	const shared = "crypto key shared sign-verify synthetic-jwks-shared-secret"
	const rsa = "crypto key signing sign-verify from file ../../testdata/rskeys/test_2_pri.pem"
	for _, tc := range []struct {
		name       string
		directives []string
	}{
		{"HMAC", []string{shared}},
		{"HMAC before RSA", []string{shared, rsa}},
		{"public verifier", []string{"crypto key verify from file ../../testdata/rskeys/test_2_pub.pem"}},
		{"system only", []string{"crypto key internal system 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := newJWKSPortal(t, tc.directives...)
			for _, method := range []string{"GET", "HEAD"} {
				w := requestJWKS(t, p, method, "/xauth/.well-known/jwks.json", nil)
				if w.Code != http.StatusNotFound || w.Body.Len() != 0 {
					t.Fatal("non-asymmetric issuer published JWKS")
				}
			}
		})
	}
	p := newJWKSPortal(t)
	p.keystore = nil
	if w := requestJWKS(t, p, "GET", jwksPath, nil); w.Code != http.StatusNotFound {
		t.Fatal("missing keystore should return 404")
	}
	p = newJWKSPortal(t)
	p.keystore.GetSignKeys()[0].Sign.Secret = []byte("synthetic-invalid-private-key")
	for _, method := range []string{"GET", "HEAD"} {
		w := requestJWKS(t, p, method, jwksPath, nil)
		if w.Code != http.StatusInternalServerError || w.Body.Len() != 0 {
			t.Fatal("invalid signer must fail without key material or errors in the response")
		}
	}
}

func TestPortalJWKSRouteBoundaries(t *testing.T) {
	p := newRefreshPortal(t, false, false).portal
	for _, target := range []string{
		"/xauth/.well-known/jwks.json/",
		"/xauth/.well-known/jwks.json.bak",
		"/xauth/.well-known/jwks.json/extra",
		"/xauth/prefix.well-known/jwks.json",
		"/xauth/.well-known/jwks.json%2fextra",
		"/xauth/unknown?path=/.well-known/jwks.json",
	} {
		t.Run(target, func(t *testing.T) {
			r := httptest.NewRequest("GET", "https://auth.example.test"+target, nil)
			w := httptest.NewRecorder()
			if err := p.ServeHTTP(context.Background(), w, r, requests.NewRequest()); err != nil {
				t.Fatal(err)
			}
			if w.Code != http.StatusNotFound {
				t.Fatalf("near-match route returned %d", w.Code)
			}
		})
	}
}

func TestPortalJWKSVerifiesLogin(t *testing.T) {
	for _, tc := range []struct {
		name, base string
		directives []string
	}{
		{"autogenerated", "", nil},
		{"RSA", "/xauth", []string{"crypto key signing-rsa sign-verify from file ../../testdata/rskeys/test_2_pri.pem"}},
		{"ECDSA", "/tenant/xauth", []string{"crypto key signing-ec sign-verify from file ../../testdata/ecdsakeys/test_2_pri.pem"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			f := newRefreshPortal(t, false, false)
			p := f.portal
			cfg, err := kms.NewCryptoKeyStoreConfig(tc.directives)
			if err != nil {
				t.Fatal(err)
			}
			p.config.CryptoKeyStoreConfig = cfg
			if err := p.configureCryptoKeyStore(); err != nil {
				t.Fatal(err)
			}
			// Fetch public keys before authenticating, then perform real portal
			// password login at the same mount and verify the issued JWT.
			w := requestJWKS(t, p, "GET", tc.base+jwksPath, nil)
			if w.Code != http.StatusOK {
				t.Fatalf("JWKS returned %d", w.Code)
			}
			b, _ := json.Marshal(apiauth.AuthRequest{Username: tests.TestUser1, Realm: "local"})
			begin := decodeAuth(t, f.request(t, "POST", tc.base+"/login", string(b), false))
			b, _ = json.Marshal(apiauth.AuthRequest{Username: tests.TestUser1, Realm: "local", SandboxID: begin.SandboxID, SandboxSecret: begin.SandboxSecret, ChallengeKind: "password", ChallengeResponse: tests.TestPwd1})
			login := decodeAuth(t, f.request(t, "POST", tc.base+"/login", string(b), false))
			if !login.Authenticated || login.AccessToken == "" {
				t.Fatal("password login did not issue an access token")
			}
			verifyPortalJWKSToken(t, w.Body.Bytes(), login.AccessToken)
			after := requestJWKS(t, p, "GET", tc.base+jwksPath, map[string]string{"Authorization": "Bearer " + login.AccessToken})
			if !bytes.Equal(w.Body.Bytes(), after.Body.Bytes()) {
				t.Fatal("login changed published keys")
			}
		})
	}
}

func verifyPortalJWKSToken(t *testing.T, data []byte, token string) {
	t.Helper()
	var set struct {
		Keys []map[string]string `json:"keys"`
	}
	if err := json.Unmarshal(data, &set); err != nil {
		t.Fatal(err)
	}
	if len(set.Keys) != 1 {
		t.Fatal("expected one signing key")
	}
	key := set.Keys[0]
	decode := func(value string) *big.Int {
		b, err := base64.RawURLEncoding.DecodeString(value)
		if err != nil {
			t.Fatal(err)
		}
		return new(big.Int).SetBytes(b)
	}
	var public any
	switch key["kty"] {
	case "RSA":
		public = &rsa.PublicKey{N: decode(key["n"]), E: int(decode(key["e"]).Int64())}
	case "EC":
		curves := map[string]elliptic.Curve{"P-256": elliptic.P256(), "P-384": elliptic.P384(), "P-521": elliptic.P521()}
		public = &ecdsa.PublicKey{Curve: curves[key["crv"]], X: decode(key["x"]), Y: decode(key["y"])}
	default:
		t.Fatal("unexpected signing key type")
	}
	parsed, err := jwtlib.Parse(token, func(token *jwtlib.Token) (any, error) {
		kid, _ := token.Header["kid"].(string)
		if kid != key["kid"] {
			t.Fatal("JWT and JWKS key IDs do not match")
		}
		return public, nil
	}, jwtlib.WithValidMethods([]string{key["alg"]}))
	if err != nil || !parsed.Valid {
		t.Fatalf("public JWKS could not verify portal token: %v", err)
	}
}

func TestPortalJWKSConcurrent(t *testing.T) {
	p := newJWKSPortal(t)
	expected := requestJWKS(t, p, "GET", jwksPath, nil).Body.Bytes()
	var wg sync.WaitGroup
	failures := make(chan error, 16)
	for range 16 {
		wg.Go(func() {
			r := httptest.NewRequest("GET", "/xauth"+jwksPath, nil)
			w := httptest.NewRecorder()
			if err := p.ServeHTTP(context.Background(), w, r, requests.NewRequest()); err != nil {
				failures <- err
				return
			}
			if w.Code != 200 || !bytes.Equal(expected, w.Body.Bytes()) {
				failures <- errors.New("concurrent JWKS response changed")
			}
		})
	}
	wg.Wait()
	close(failures)
	for err := range failures {
		t.Error(err)
	}
}

type jwksFailingWriter struct {
	*httptest.ResponseRecorder
	err error
}

func (w jwksFailingWriter) Write(_ []byte) (int, error) { return 0, w.err }

func TestPortalJWKSWriteError(t *testing.T) {
	p := newJWKSPortal(t)
	want := errors.New("connection closed")
	w := jwksFailingWriter{httptest.NewRecorder(), want}
	r := httptest.NewRequest("GET", jwksPath, nil)
	if err := p.ServeHTTP(context.Background(), w, r, requests.NewRequest()); !errors.Is(err, want) {
		t.Fatal("response write error was not propagated")
	}
}
