// Copyright 2026 Paul Greenberg greenpau@outlook.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kms

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"

	jwtlib "github.com/golang-jwt/jwt/v5"
	"go.uber.org/zap"

	"github.com/greenpau/go-authcrunch/pkg/user"
)

func newJWKSStore(t *testing.T, directives ...string) *CryptoKeyStore {
	t.Helper()
	cfg, err := NewCryptoKeyStoreConfig(directives)
	if err != nil {
		t.Fatal(err)
	}
	ks, err := NewCryptoKeyStore(cfg, zap.NewNop())
	if err != nil {
		t.Fatal(err)
	}
	return ks
}

func decodePublicJWKS(t *testing.T, data []byte) []publicJSONWebKey {
	t.Helper()
	// Decode independently to reject every field that could disclose secrets.
	var document map[string][]map[string]string
	if err := json.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	if len(document) != 1 || len(document["keys"]) == 0 {
		t.Fatal("expected a nonempty JWK Set")
	}
	for _, key := range document["keys"] {
		allowed := map[string]bool{"kty": true, "use": true, "alg": true, "kid": true}
		switch key["kty"] {
		case "RSA":
			allowed["n"], allowed["e"] = true, true
		case "EC":
			allowed["crv"], allowed["x"], allowed["y"] = true, true, true
		default:
			t.Fatal("unexpected public key type")
		}
		for field := range key {
			if !allowed[field] {
				t.Fatalf("unexpected JWK field %q", field)
			}
		}
		if key["use"] != "sig" {
			t.Fatal("expected signature key use")
		}
	}
	var set struct {
		Keys []publicJSONWebKey `json:"keys"`
	}
	if err := json.Unmarshal(data, &set); err != nil {
		t.Fatal(err)
	}
	return set.Keys
}

func verifyJWKSToken(t *testing.T, key publicJSONWebKey, token string) {
	t.Helper()
	decode := func(s string) []byte {
		b, err := base64.RawURLEncoding.DecodeString(s)
		if err != nil {
			t.Fatal(err)
		}
		return b
	}
	var publicKey any
	switch key.KeyType {
	case "RSA":
		n, e := decode(key.N), decode(key.E)
		if len(n) == 0 || n[0] == 0 || len(e) == 0 || e[0] == 0 {
			t.Fatal("non-minimal RSA integer encoding")
		}
		publicKey = &rsa.PublicKey{N: new(big.Int).SetBytes(n), E: int(new(big.Int).SetBytes(e).Int64())}
	case "EC":
		curves := map[string]elliptic.Curve{"P-256": elliptic.P256(), "P-384": elliptic.P384(), "P-521": elliptic.P521()}
		curve := curves[key.Curve]
		if curve == nil {
			t.Fatal("unexpected curve")
		}
		x, y := decode(key.X), decode(key.Y)
		width := (curve.Params().BitSize + 7) / 8
		if len(x) != width || len(y) != width {
			t.Fatal("EC coordinates are not fixed width")
		}
		publicKey = &ecdsa.PublicKey{Curve: curve, X: new(big.Int).SetBytes(x), Y: new(big.Int).SetBytes(y)}
	}
	parsed, err := jwtlib.Parse(token, func(token *jwtlib.Token) (any, error) {
		kid, _ := token.Header["kid"].(string)
		if kid != key.KeyID {
			t.Fatal("JWT and JWK key IDs differ")
		}
		return publicKey, nil
	}, jwtlib.WithValidMethods([]string{key.Algorithm}))
	if err != nil || !parsed.Valid {
		t.Fatalf("published key cannot verify issued token: %v", err)
	}
	if parsed.Claims.(jwtlib.MapClaims)["sub"] != "jwks-test" {
		t.Fatal("unexpected signed subject")
	}
}

func newJWKSUser(t *testing.T) *user.User {
	t.Helper()
	u, err := user.NewUser(map[string]any{"sub": "jwks-test", "exp": time.Now().Add(time.Hour).Unix()})
	if err != nil {
		t.Fatal(err)
	}
	return u
}

func TestCryptoKeyStoreJWKS(t *testing.T) {
	const rsaKey = "crypto key rsa-signing sign-verify from file ../../testdata/rskeys/test_2_pri.pem"
	const ecKey = "crypto key ec-signing sign-verify from file ../../testdata/ecdsakeys/test_2_pri.pem"
	const hmacKey = "crypto key shared sign-verify synthetic-jwks-shared-secret"
	const systemKey = "crypto key internal system 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	cases := []struct {
		name       string
		directives []string
		ids        []string
	}{
		{"autogenerated", nil, []string{""}},
		{"RSA", []string{rsaKey}, []string{"rsa-signing"}},
		{"EC", []string{ecKey}, []string{"ec-signing"}},
		{"multiple signing keys", []string{rsaKey, ecKey}, []string{"rsa-signing", "ec-signing"}},
		{"shared secret", []string{hmacKey}, nil},
		{"shared issuer with asymmetric fallback", []string{hmacKey, rsaKey}, nil},
		{"asymmetric issuer with shared fallback", []string{rsaKey, hmacKey}, []string{"rsa-signing"}},
		{"verification only RSA", []string{"crypto key verify from file ../../testdata/rskeys/test_2_pub.pem"}, nil},
		{"verification only EC", []string{"crypto key verify from file ../../testdata/ecdsakeys/test_2_pub.pem"}, nil},
		{"foreign verifier excluded", []string{rsaKey, "crypto key external verify from file ../../testdata/ecdsakeys/test_2_pub.pem"}, []string{"rsa-signing"}},
		{"sign only", []string{"crypto key rsa-signing sign from file ../../testdata/rskeys/test_2_pri.pem"}, []string{"rsa-signing"}},
		{"separate sign and verify", []string{"crypto key rsa-signing sign from file ../../testdata/rskeys/test_2_pri.pem", "crypto key rsa-signing verify from file ../../testdata/rskeys/test_2_pub.pem"}, []string{"rsa-signing"}},
		{"system only", []string{systemKey}, nil},
		{"system before shared issuer", []string{systemKey, hmacKey}, nil},
		{"system before asymmetric issuer", []string{systemKey, rsaKey}, []string{"rsa-signing"}},
		{"duplicate key", []string{rsaKey, rsaKey}, []string{"rsa-signing"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ks := newJWKSStore(t, tc.directives...)
			data, err := ks.GetJWKS()
			if err != nil {
				t.Fatal(err)
			}
			if len(tc.ids) == 0 {
				if data != nil {
					t.Fatal("issuer without asymmetric signing published a JWKS")
				}
				return
			}
			keys := decodePublicJWKS(t, data)
			if len(keys) != len(tc.ids) {
				t.Fatalf("got %d keys, want %d", len(keys), len(tc.ids))
			}
			for i, key := range keys {
				if key.KeyID != tc.ids[i] {
					t.Fatalf("unexpected key ID %q", key.KeyID)
				}
				if tc.name == "autogenerated" && (key.Algorithm != "ES512" || key.Curve != "P-521") {
					t.Fatal("default autogenerated signer must be ES512/P-521")
				}
				// Verify each published key against the actual signing operator.
				for _, signer := range ks.GetSignKeys() {
					if signer.Config.Usage == "system" {
						continue
					}
					id := ""
					if signer.Sign.Token.injectKeyID {
						id = signer.Sign.Token.ID
					}
					if id != key.KeyID {
						continue
					}
					u := newJWKSUser(t)
					if err := signer.SignToken(nil, u); err != nil {
						t.Fatal(err)
					}
					verifyJWKSToken(t, key, u.Token)
					break
				}
			}
			u := newJWKSUser(t)
			if err := ks.SignToken(nil, nil, u); err != nil {
				t.Fatal(err)
			}
			verifyJWKSToken(t, keys[0], u.Token)
			again, err := ks.GetJWKS()
			if err != nil || !bytes.Equal(data, again) {
				t.Fatal("JWKS response is not stable")
			}
		})
	}
	for _, ks := range []*CryptoKeyStore{nil, {}} {
		data, err := ks.GetJWKS()
		if err != nil || data != nil {
			t.Fatal("empty keystore should not publish JWKS")
		}
	}
}

func TestCryptoKeyStoreJWKSRSAAlgorithms(t *testing.T) {
	for _, algorithm := range []string{"RS256", "RS384", "RS512"} {
		t.Run(algorithm, func(t *testing.T) {
			ks := newJWKSStore(t, "crypto key sign-verify from file ../../testdata/rskeys/test_2_pri.pem")
			ks.signKeys[0].Sign.Token.DefaultMethod = algorithm
			data, err := ks.GetJWKS()
			if err != nil {
				t.Fatal(err)
			}
			key := decodePublicJWKS(t, data)[0]
			if key.Algorithm != algorithm || key.E != "AQAB" {
				t.Fatal("incorrect RSA JWK metadata")
			}
			u := newJWKSUser(t)
			if err := ks.SignToken(nil, nil, u); err != nil {
				t.Fatal(err)
			}
			verifyJWKSToken(t, key, u.Token)
		})
	}
}

func TestCryptoKeyStoreJWKSECCoordinatePadding(t *testing.T) {
	for _, curve := range []elliptic.Curve{elliptic.P256(), elliptic.P384(), elliptic.P521()} {
		t.Run(curve.Params().Name, func(t *testing.T) {
			// Construct a synthetic key with a leading zero coordinate. This
			// deterministically catches accidental use of big.Int.Bytes().
			width := (curve.Params().BitSize + 7) / 8
			var private *ecdsa.PrivateKey
			for scalar := int64(1); scalar < 10000; scalar++ {
				d := big.NewInt(scalar)
				x, y := curve.ScalarBaseMult(d.Bytes())
				if len(x.Bytes()) < width || len(y.Bytes()) < width {
					private = &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: curve, X: x, Y: y}, D: d}
					break
				}
			}
			if private == nil {
				t.Fatal("failed to construct leading-zero coordinate fixture")
			}
			der, err := x509.MarshalECPrivateKey(private)
			if err != nil {
				t.Fatal(err)
			}
			filename := filepath.Join(t.TempDir(), "private.pem")
			if err := os.WriteFile(filename, pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: der}), 0600); err != nil {
				t.Fatal(err)
			}
			ks := newJWKSStore(t, fmt.Sprintf("crypto key curve-key sign from file %s", filename))
			data, err := ks.GetJWKS()
			if err != nil {
				t.Fatal(err)
			}
			key := decodePublicJWKS(t, data)[0]
			u := newJWKSUser(t)
			if err := ks.SignToken(nil, nil, u); err != nil {
				t.Fatal(err)
			}
			verifyJWKSToken(t, key, u.Token)
		})
	}
}

func TestCryptoKeyStoreJWKSInvalidSigner(t *testing.T) {
	p256 := elliptic.P256()
	x, y := p256.ScalarBaseMult([]byte{1})
	cases := []struct {
		name, method string
		secret       any
	}{
		{"unsupported material", "RS512", []byte("synthetic-private-material")},
		{"nil RSA", "RS512", (*rsa.PrivateKey)(nil)},
		{"missing modulus", "RS512", &rsa.PrivateKey{}},
		{"invalid exponent", "RS512", &rsa.PrivateKey{PublicKey: rsa.PublicKey{N: big.NewInt(17)}}},
		{"wrong RSA algorithm", "ES512", &rsa.PrivateKey{PublicKey: rsa.PublicKey{N: big.NewInt(17), E: 3}}},
		{"nil EC", "ES256", (*ecdsa.PrivateKey)(nil)},
		{"missing curve", "ES256", &ecdsa.PrivateKey{}},
		{"missing coordinate", "ES256", &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: p256, X: x}}},
		{"unsupported curve", "ES256", &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: elliptic.P224(), X: x, Y: y}}},
		{"off curve", "ES256", &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: p256, X: big.NewInt(0), Y: big.NewInt(0)}}},
		{"wrong EC algorithm", "ES384", &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: p256, X: x, Y: y}}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ks := &CryptoKeyStore{}
			k := newCryptoKey()
			k.Config = &CryptoKeyConfig{Usage: "sign"}
			k.Sign.Capable = true
			k.Sign.Token.DefaultMethod = tc.method
			k.Sign.Secret = tc.secret
			if err := ks.AddKey(k); err != nil {
				t.Fatal(err)
			}
			data, err := ks.GetJWKS()
			if err == nil || data != nil {
				t.Fatal("invalid signer must fail without publishing keys")
			}
		})
	}
}
