// Copyright 2026 Paul Greenberg greenpau@outlook.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package kms

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"math/big"
	"sync"
	"testing"
	"time"

	jwtlib "github.com/golang-jwt/jwt/v5"

	autherrors "github.com/greenpau/go-authcrunch/pkg/errors"
)

func TestJWKSPrivateKeys(t *testing.T) {
	const rsaKey = "crypto key rsa-signing sign-verify from file ../../testdata/rskeys/test_2_pri.pem"
	const ecKey = "crypto key ec-signing sign-verify from file ../../testdata/ecdsakeys/test_2_pri.pem"
	const shared = "crypto key shared sign-verify synthetic-private-export-shared-secret"
	const systemKey = "crypto key internal system 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	for _, tc := range []struct {
		name       string
		directives []string
		count      int
	}{
		{"autogenerated", nil, 1},
		{"RSA", []string{rsaKey}, 1},
		{"EC", []string{ecKey}, 1},
		{"multiple keys", []string{rsaKey, ecKey}, 2},
		{"sign only", []string{"crypto key sign from file ../../testdata/rskeys/test_2_pri.pem"}, 1},
		{"duplicate", []string{rsaKey, rsaKey}, 1},
		{"excluded keys", []string{systemKey, rsaKey, ecKey, shared, "crypto key foreign verify from file ../../testdata/rskeys/test_2_pub.pem"}, 2},
		{"shared", []string{shared}, 0},
		{"shared issuer", []string{shared, rsaKey}, 0},
		{"verification only", []string{"crypto key verify from file ../../testdata/rskeys/test_2_pub.pem"}, 0},
		{"system only", []string{systemKey}, 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ks := newJWKSStore(t, tc.directives...)
			public, err := ks.GetJWKS()
			if err != nil {
				t.Fatal(err)
			}
			data, err := ks.GetJWKSPrivateKeys("", "")
			if err != nil {
				t.Fatal(err)
			}
			if tc.count == 0 {
				if data != nil || public != nil {
					t.Fatal("unpublished keys were exported")
				}
				return
			}
			var set struct {
				Keys []jwksPrivateKey `json:"keys"`
			}
			if err := json.Unmarshal(data, &set); err != nil {
				t.Fatal("invalid private-key response JSON")
			}
			if len(set.Keys) != tc.count {
				t.Fatal("incorrect exported key count")
			}
			publicKeys := decodePublicJWKS(t, public)
			for i, key := range set.Keys {
				if key.PublicKey != publicKeys[i] {
					t.Fatal("exported key is not associated with the public JWKS")
				}
				var privatePEM string
				if err := json.Unmarshal(key.PrivateKey, &privatePEM); err != nil {
					t.Fatal("expected PEM string")
				}
				block, rest := pem.Decode([]byte(privatePEM))
				if block == nil || block.Type != "PRIVATE KEY" || len(rest) != 0 {
					t.Fatal("expected one PKCS#8 PEM block")
				}
				private, err := x509.ParsePKCS8PrivateKey(block.Bytes)
				if err != nil {
					t.Fatal("exported private key is not valid PKCS#8")
				}
				token := jwtlib.NewWithClaims(jwtlib.GetSigningMethod(key.PublicKey.Algorithm), jwtlib.MapClaims{"sub": "jwks-test", "exp": time.Now().Add(time.Hour).Unix()})
				if key.PublicKey.KeyID != "" {
					token.Header["kid"] = key.PublicKey.KeyID
				}
				signed, err := token.SignedString(private)
				if err != nil {
					t.Fatal("exported key cannot sign")
				}
				verifyJWKSToken(t, key.PublicKey, signed)
			}
			after, err := ks.GetJWKS()
			if err != nil || !bytes.Equal(public, after) {
				t.Fatal("private export changed the public JWKS")
			}
			decodePublicJWKS(t, after)
		})
	}
	for _, ks := range []*CryptoKeyStore{nil, {}} {
		data, err := ks.GetJWKSPrivateKeys("", "")
		if data != nil || err != nil {
			t.Fatal("empty store exported keys")
		}
	}
}

func TestJWKSPrivateKeysInvalidMaterial(t *testing.T) {
	for _, tc := range []struct {
		name   string
		change func(*CryptoKey)
	}{
		{"invalid public material", func(k *CryptoKey) { k.Sign.Secret = []byte("synthetic-invalid-secret") }},
		{"missing private scalar", func(k *CryptoKey) { copy := *k.Sign.Secret.(*ecdsa.PrivateKey); copy.D = nil; k.Sign.Secret = &copy }},
		{"mismatched private scalar", func(k *CryptoKey) {
			copy := *k.Sign.Secret.(*ecdsa.PrivateKey)
			copy.D = big.NewInt(2)
			k.Sign.Secret = &copy
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ks := newJWKSStore(t)
			tc.change(ks.GetSignKeys()[0])
			data, err := ks.GetJWKSPrivateKeys("", "")
			if err == nil || data != nil {
				t.Fatal("invalid private material was exported")
			}
		})
	}
	t.Run("partial response discarded", func(t *testing.T) {
		ks := newJWKSStore(t,
			"crypto key ec sign-verify from file ../../testdata/ecdsakeys/test_2_pri.pem",
			"crypto key rsa sign-verify from file ../../testdata/rskeys/test_2_pri.pem")
		copy := *ks.GetSignKeys()[1].Sign.Secret.(*rsa.PrivateKey)
		copy.D = nil
		ks.GetSignKeys()[1].Sign.Secret = &copy
		data, err := ks.GetJWKSPrivateKeys("", "")
		if err == nil || data != nil {
			t.Fatal("failure returned a partial set of private keys")
		}
	})
}

func TestJWKSPrivateKeysConcurrent(t *testing.T) {
	ks := newJWKSStore(t, "crypto key sign-verify from file ../../testdata/rskeys/test_2_pri.pem")
	key := ks.GetSignKeys()[0].Sign.Secret.(*rsa.PrivateKey)
	key.Precomputed = rsa.PrecomputedValues{}
	// Include concurrent signing of a non-precomputed key to expose accidental
	// mutation by x509's private-key marshaler.
	var wg sync.WaitGroup
	for range 8 {
		wg.Go(func() {
			if data, err := ks.GetJWKSPrivateKeys("", ""); err != nil || len(data) == 0 {
				t.Error("concurrent export failed")
			}
		})
		wg.Go(func() {
			token := jwtlib.NewWithClaims(jwtlib.SigningMethodRS512, jwtlib.MapClaims{"sub": "jwks-test"})
			if _, err := token.SignedString(key); err != nil {
				t.Error("concurrent signing failed")
			}
		})
	}
	wg.Wait()
	if key.Precomputed.Dp != nil || key.Precomputed.Dq != nil || key.Precomputed.Qinv != nil {
		t.Fatal("export mutated RSA precomputation")
	}
}

func verifyPrivateKeyExport(t *testing.T, data []byte, format, encoding string) {
	t.Helper()
	var set struct {
		Keys []jwksPrivateKey `json:"keys"`
	}
	if err := json.Unmarshal(data, &set); err != nil {
		t.Fatal("invalid private-key export")
	}
	if len(set.Keys) == 0 {
		t.Fatal("empty private-key export")
	}
	for _, key := range set.Keys {
		var private any
		var err error
		if format == "jwk" {
			var jwk privateJSONWebKey
			if err := json.Unmarshal(key.PrivateKey, &jwk); err != nil {
				t.Fatal("invalid private JWK")
			}
			if jwk.publicJSONWebKey != key.PublicKey {
				t.Fatal("private JWK public parameters differ")
			}
			decode := func(value string) *big.Int {
				b, err := base64.RawURLEncoding.DecodeString(value)
				if err != nil || len(b) == 0 {
					t.Fatal("invalid JWK private parameter")
				}
				return new(big.Int).SetBytes(b)
			}
			if jwk.KeyType == "RSA" {
				rsaKey := &rsa.PrivateKey{PublicKey: rsa.PublicKey{N: decode(jwk.N), E: int(decode(jwk.E).Int64())}, D: decode(jwk.D), Primes: []*big.Int{decode(jwk.P), decode(jwk.Q)}}
				for _, prime := range jwk.OtherPrimes {
					rsaKey.Primes = append(rsaKey.Primes, decode(prime.R))
				}
				rsaKey.Precompute()
				if err := rsaKey.Validate(); err != nil {
					t.Fatal("invalid exported RSA JWK")
				}
				if rsaKey.Precomputed.Dp.Cmp(decode(jwk.DP)) != 0 || rsaKey.Precomputed.Dq.Cmp(decode(jwk.DQ)) != 0 || rsaKey.Precomputed.Qinv.Cmp(decode(jwk.QI)) != 0 {
					t.Fatal("invalid RSA JWK CRT parameters")
				}
				for i, prime := range jwk.OtherPrimes {
					if rsaKey.Precomputed.CRTValues[i].Exp.Cmp(decode(prime.D)) != 0 || rsaKey.Precomputed.CRTValues[i].Coeff.Cmp(decode(prime.T)) != 0 {
						t.Fatal("invalid additional-prime CRT parameters")
					}
				}
				private = rsaKey
			} else {
				curves := map[string]elliptic.Curve{"P-256": elliptic.P256(), "P-384": elliptic.P384(), "P-521": elliptic.P521()}
				curve := curves[jwk.Curve]
				b, err := base64.RawURLEncoding.DecodeString(jwk.D)
				if curve == nil || err != nil || len(b) != (curve.Params().N.BitLen()+7)/8 {
					t.Fatal("EC private scalar is not fixed width")
				}
				private = &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: curve, X: decode(jwk.X), Y: decode(jwk.Y)}, D: decode(jwk.D)}
			}
		} else {
			var value string
			if err := json.Unmarshal(key.PrivateKey, &value); err != nil {
				t.Fatal("expected encoded private-key string")
			}
			var der []byte
			if encoding == "der" {
				der, err = base64.StdEncoding.DecodeString(value)
				if err != nil {
					t.Fatal("DER is not standard base64")
				}
			} else {
				block, rest := pem.Decode([]byte(value))
				if block == nil || len(rest) != 0 {
					t.Fatal("invalid private PEM")
				}
				types := map[string]string{"pkcs8": "PRIVATE KEY", "pkcs1": "RSA PRIVATE KEY", "sec1": "EC PRIVATE KEY"}
				if block.Type != types[format] {
					t.Fatal("incorrect PEM type")
				}
				der = block.Bytes
			}
			switch format {
			case "pkcs8":
				private, err = x509.ParsePKCS8PrivateKey(der)
			case "pkcs1":
				private, err = x509.ParsePKCS1PrivateKey(der)
			case "sec1":
				private, err = x509.ParseECPrivateKey(der)
			}
			if err != nil {
				t.Fatal("private key did not parse in the requested format")
			}
		}
		token := jwtlib.NewWithClaims(jwtlib.GetSigningMethod(key.PublicKey.Algorithm), jwtlib.MapClaims{"sub": "jwks-test", "exp": time.Now().Add(time.Hour).Unix()})
		if key.PublicKey.KeyID != "" {
			token.Header["kid"] = key.PublicKey.KeyID
		}
		signed, err := token.SignedString(private)
		if err != nil {
			t.Fatal("exported private key cannot sign")
		}
		verifyJWKSToken(t, key.PublicKey, signed)
	}
}

func TestJWKSPrivateKeyFormats(t *testing.T) {
	for _, keyType := range []string{"RSA", "EC"} {
		t.Run(keyType, func(t *testing.T) {
			var ks *CryptoKeyStore
			formats := []string{"pkcs8", "jwk"}
			if keyType == "RSA" {
				ks = newJWKSStore(t, "crypto key signing sign-verify from file ../../testdata/rskeys/test_2_pri.pem")
				formats = append(formats, "pkcs1")
			} else {
				ks = newJWKSStore(t)
				formats = append(formats, "sec1")
			}
			for _, format := range formats {
				encodings := []string{"pem", "der"}
				if format == "jwk" {
					encodings = []string{"", "json"}
				}
				for _, encoding := range encodings {
					t.Run(format+"/"+encoding, func(t *testing.T) {
						data, err := ks.GetJWKSPrivateKeys(format, encoding)
						if err != nil {
							t.Fatal(err)
						}
						verifyPrivateKeyExport(t, data, format, encoding)
					})
				}
			}
		})
	}
	for _, curve := range []elliptic.Curve{elliptic.P256(), elliptic.P384(), elliptic.P521()} {
		t.Run(curve.Params().Name, func(t *testing.T) {
			ks := newJWKSStore(t)
			x, y := curve.ScalarBaseMult([]byte{1})
			key := ks.GetSignKeys()[0]
			key.Sign.Secret = &ecdsa.PrivateKey{PublicKey: ecdsa.PublicKey{Curve: curve, X: x, Y: y}, D: big.NewInt(1)}
			key.Sign.Token.DefaultMethod = map[string]string{"P-256": "ES256", "P-384": "ES384", "P-521": "ES512"}[curve.Params().Name]
			data, err := ks.GetJWKSPrivateKeys("jwk", "")
			if err != nil {
				t.Fatal(err)
			}
			verifyPrivateKeyExport(t, data, "jwk", "")
		})
	}
	t.Run("multiprime RSA", func(t *testing.T) {
		private, err := rsa.GenerateMultiPrimeKey(rand.Reader, 3, 2048)
		if err != nil {
			t.Fatal("could not generate synthetic multiprime key")
		}
		ks := newJWKSStore(t, "crypto key signing sign-verify from file ../../testdata/rskeys/test_2_pri.pem")
		ks.GetSignKeys()[0].Sign.Secret = private
		data, err := ks.GetJWKSPrivateKeys("jwk", "")
		if err != nil {
			t.Fatal(err)
		}
		verifyPrivateKeyExport(t, data, "jwk", "")
	})
}

func TestJWKSPrivateKeyFormatErrors(t *testing.T) {
	ks := newJWKSStore(t)
	for _, tc := range []struct {
		format, encoding string
		err              error
	}{
		{"xml", "", autherrors.ErrPrivateKeyExportFormat},
		{"pkcs8", "raw", autherrors.ErrPrivateKeyExportEncoding},
		{"pkcs8", "json", autherrors.ErrPrivateKeyExportEncoding},
		{"jwk", "pem", autherrors.ErrPrivateKeyExportEncoding},
		{"jwk", "der", autherrors.ErrPrivateKeyExportEncoding},
		{"pkcs1", "", autherrors.ErrPrivateKeyExportKeyType},
	} {
		data, err := ks.GetJWKSPrivateKeys(tc.format, tc.encoding)
		if !errors.Is(err, tc.err) || data != nil {
			t.Fatal("invalid export options did not fail atomically")
		}
	}
	mixed := newJWKSStore(t,
		"crypto key rsa-signing sign-verify from file ../../testdata/rskeys/test_2_pri.pem",
		"crypto key ec-signing sign-verify from file ../../testdata/ecdsakeys/test_2_pri.pem")
	for _, format := range []string{"pkcs1", "sec1"} {
		data, err := mixed.GetJWKSPrivateKeys(format, "")
		if !errors.Is(err, autherrors.ErrPrivateKeyExportKeyType) || data != nil {
			t.Fatal("mixed key types produced an incomplete format-specific export")
		}
	}
}
