// Copyright 2026 Paul Greenberg greenpau@outlook.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package parser decodes OIDC configuration directives independently of an
// embedding server and provisions validated, reusable client registrations.
package parser

import (
	"fmt"
	"slices"
	"strings"

	"github.com/greenpau/go-authcrunch/pkg/oidc"
	cfgutil "github.com/greenpau/go-authcrunch/pkg/util/cfg"
)

// NewOIDCClientConfigFromDirectives decodes an "oauth application <nickname>"
// block body and provisions its client registration. Statements use
// cfgutil.EncodeArgs/cfgutil.DecodeArgs encoding, as crypto directives do. Pass
// only the block's directive lines, without its header or braces. Nickname supplies
// ClientName unless a client_name directive overrides it; the embedding
// application owns lookup and uniqueness of configuration nicknames.
//
// Each redirect_uri statement takes exactly one callback URI; repeat it to
// register multiple callbacks in declaration order. The plural redirect_uris
// directive is unsupported; that spelling belongs to the serialized array.
// Other directives occur once: client_id, client_name, client_secret, and
// token_endpoint_auth_method take one value; scopes takes one or more.
// require_pkce and skip_consent each take one cfgutil.ParseBoolArg value.
// PKCE defaults to true; only confidential clients may explicitly disable it.
// A none client with an HTTP literal-loopback callback registers the supported
// native subset: authorization may vary its valid TCP port only. Token exchange
// must send the actual authorized URI. HTTPS callbacks remain exact.
// Unknown directives, duplicate settings/URIs, empty values, and malformed
// lines fail without echoing credentials. Quoted values retain their contents
// after decoding.
//
// Missing credentials are generated by oidc.NewClientConfig. Persist the result
// and supply its credentials on subsequent adaptations; calling this function
// with missing credentials every time creates a new registration every time.
// This does not update a running provider or create its signing keys.
func NewOIDCClientConfigFromDirectives(nickname string, statements []string) (*oidc.ClientConfig, error) {
	config, err := parseOIDCClientConfigFromDirectives(nickname, statements)
	if err != nil {
		return nil, err
	}
	client, err := oidc.NewClientConfig(*config)
	if err != nil {
		return nil, err
	}
	client.RequirePKCE = config.RequirePKCE
	return client, nil
}

// Keep application field decoding in one place for explicit provisioning and
// adaptation with persisted credentials. Neither path may bypass syntax checks.
func parseOIDCClientConfigFromDirectives(nickname string, statements []string) (*oidc.ClientConfig, error) {
	if nickname == "" || len(nickname) > 256 || strings.TrimSpace(nickname) != nickname || strings.ContainsAny(nickname, "\r\n\t") {
		return nil, fmt.Errorf("invalid oidc application nickname")
	}
	config := oidc.ClientConfig{ClientName: nickname, RequirePKCE: true}
	seen := make(map[string]bool)
	for i, statement := range statements {
		// DecodeArgs reads one CSV record. Reject embedded newlines so a second
		// directive cannot be silently discarded after that record.
		if strings.ContainsAny(statement, "\r\n") {
			return nil, fmt.Errorf("invalid oidc application directive at line %d", i+1)
		}
		args, err := cfgutil.DecodeArgs(statement)
		if err != nil || len(args) < 2 {
			return nil, fmt.Errorf("invalid oidc application directive at line %d", i+1)
		}
		key := args[0]
		switch key {
		case "scopes":
		case "redirect_uri", "client_id", "client_name", "client_secret", "token_endpoint_auth_method", "require_pkce", "skip_consent":
			if len(args) != 2 {
				return nil, fmt.Errorf("oidc application directive %s at line %d requires one value", key, i+1)
			}
		default:
			return nil, fmt.Errorf("unsupported oidc application directive at line %d", i+1)
		}
		if seen[key] && key != "redirect_uri" {
			return nil, fmt.Errorf("duplicate oidc application directive %s at line %d", key, i+1)
		}
		seen[key] = true
		if slices.Contains(args[1:], "") {
			return nil, fmt.Errorf("empty oidc application directive %s value at line %d", key, i+1)
		}
		switch key {
		case "client_id":
			config.ClientID = args[1]
		case "client_name":
			config.ClientName = args[1]
		case "client_secret":
			config.ClientSecret = args[1]
		case "token_endpoint_auth_method":
			config.TokenEndpointAuthMethod = args[1]
		case "redirect_uri":
			config.RedirectURIs = append(config.RedirectURIs, args[1])
		case "scopes":
			config.Scopes = args[1:]
		case "require_pkce", "skip_consent":
			value, err := cfgutil.ParseBoolArg(args[1])
			if err != nil {
				// ParseBoolArg errors contain the value; do not propagate it.
				return nil, fmt.Errorf("invalid oidc application boolean %s at line %d", key, i+1)
			}
			if key == "require_pkce" {
				config.RequirePKCE = value
			} else {
				config.SkipConsent = value
			}
		}
	}
	if config.TokenEndpointAuthMethod == "none" && !config.RequirePKCE {
		return nil, fmt.Errorf("public oidc clients require PKCE")
	}
	return &config, nil
}
